# SPDX-License-Identifier: GPL-2.0-only

# Do we need this?
#ccflags-y += -I$(srctree)

obj-$(CONFIG_PIXEL_METRICS) += pixel_metrics.o
pixel_metrics-y += perf_metrics.o init_metrics.o thermal_metrics.o

