subdir-ccflags-y += -I$(srctree)/$(src)
subdir-ccflags-y += -I$(srctree)/arch/arm64/kvm/hyp/include/

obj-m += pkvm-s2mpu.o

$(obj)/hyp/kvm_nvhe.o: FORCE
		$(Q)$(MAKE) $(build)=$(obj)/hyp $(obj)/hyp/kvm_nvhe.o

clean-files := hyp/hyp.lds hyp/hyp-reloc.S

pkvm-s2mpu-y := pkvm_s2mpu.o s2mpu.o hyp/kvm_nvhe.o
