# SPDX-License-Identifier: GPL-2.0
obj-$(CONFIG_SAMSUNG_IOMMU) += samsung_iommu.o
samsung_iommu-objs += samsung-iommu.o samsung-iommu-fault.o
obj-$(CONFIG_SAMSUNG_IOMMU_GROUP) += samsung-iommu-group.o
obj-$(CONFIG_SAMSUNG_SECURE_IOVA) += samsung-secure-iova.o
