/* SPDX-License-Identifier: GPL-2.0-only */
/*
 * Google LWIS ZUMA ISP_FE Interrupt And Event Defines
 *
 * Copyright (c) 2022 Google, LLC
 */

#ifndef DT_BINDINGS_LWIS_PLATFORM_ZUMA_ISP_FE_H_
#define DT_BINDINGS_LWIS_PLATFORM_ZUMA_ISP_FE_H_

#include <dt-bindings/lwis/platform/common.h>

/* clang-format off */

#define ISP_FE_FC_BAYER_CTX0_BASE {HW_EVENT_MASK + 0}

#define ISP_FE_FC_BAYER_CTX0_FC_SOF 0
#define ISP_FE_FC_BAYER_CTX0_FC_EOF 1
#define ISP_FE_FC_BAYER_CTX0_FC_REG_UPDATED 2
#define ISP_FE_FC_BAYER_CTX0_FC_ABORT_START 3
#define ISP_FE_FC_BAYER_CTX0_FC_ABORT_DMA_CMPLT 4
#define ISP_FE_FC_BAYER_CTX0_FC_ABORT_DONE 5
#define ISP_FE_FC_BAYER_CTX0_FC_LATE_CONFIG 6
#define ISP_FE_FC_BAYER_CTX0_FC_ERROR 7
#define ISP_FE_FC_BAYER_CTX0_SPD_WDMA_BUS_ERROR 8
#define ISP_FE_FC_BAYER_CTX0_LMP_IDMA0_BUS_ERROR 9
#define ISP_FE_FC_BAYER_CTX0_LMP_IDMA1_BUS_ERROR 10

#define ISP_FE_FC_BAYER_CTX1_BASE {HW_EVENT_MASK + 32}

#define ISP_FE_FC_BAYER_CTX1_FC_SOF 0
#define ISP_FE_FC_BAYER_CTX1_FC_EOF 1
#define ISP_FE_FC_BAYER_CTX1_FC_REG_UPDATED 2
#define ISP_FE_FC_BAYER_CTX1_FC_ABORT_START 3
#define ISP_FE_FC_BAYER_CTX1_FC_ABORT_DMA_CMPLT 4
#define ISP_FE_FC_BAYER_CTX1_FC_ABORT_DONE 5
#define ISP_FE_FC_BAYER_CTX1_FC_LATE_CONFIG 6
#define ISP_FE_FC_BAYER_CTX1_FC_ERROR 7
#define ISP_FE_FC_BAYER_CTX1_SPD_WDMA_BUS_ERROR 8
#define ISP_FE_FC_BAYER_CTX1_LMP_IDMA0_BUS_ERROR 9
#define ISP_FE_FC_BAYER_CTX1_LMP_IDMA1_BUS_ERROR 10

#define ISP_FE_FC_BAYER_CTX2_BASE {HW_EVENT_MASK + 64}

#define ISP_FE_FC_BAYER_CTX2_FC_SOF 0
#define ISP_FE_FC_BAYER_CTX2_FC_EOF 1
#define ISP_FE_FC_BAYER_CTX2_FC_REG_UPDATED 2
#define ISP_FE_FC_BAYER_CTX2_FC_ABORT_START 3
#define ISP_FE_FC_BAYER_CTX2_FC_ABORT_DMA_CMPLT 4
#define ISP_FE_FC_BAYER_CTX2_FC_ABORT_DONE 5
#define ISP_FE_FC_BAYER_CTX2_FC_LATE_CONFIG 6
#define ISP_FE_FC_BAYER_CTX2_FC_ERROR 7
#define ISP_FE_FC_BAYER_CTX2_SPD_WDMA_BUS_ERROR 8
#define ISP_FE_FC_BAYER_CTX2_LMP_IDMA0_BUS_ERROR 9
#define ISP_FE_FC_BAYER_CTX2_LMP_IDMA1_BUS_ERROR 10

#define ISP_FE_FC_BAYER_CTX3_BASE {HW_EVENT_MASK + 96}

#define ISP_FE_FC_BAYER_CTX3_FC_SOF 0
#define ISP_FE_FC_BAYER_CTX3_FC_EOF 1
#define ISP_FE_FC_BAYER_CTX3_FC_REG_UPDATED 2
#define ISP_FE_FC_BAYER_CTX3_FC_ABORT_START 3
#define ISP_FE_FC_BAYER_CTX3_FC_ABORT_DMA_CMPLT 4
#define ISP_FE_FC_BAYER_CTX3_FC_ABORT_DONE 5
#define ISP_FE_FC_BAYER_CTX3_FC_LATE_CONFIG 6
#define ISP_FE_FC_BAYER_CTX3_FC_ERROR 7
#define ISP_FE_FC_BAYER_CTX3_SPD_WDMA_BUS_ERROR 8
#define ISP_FE_FC_BAYER_CTX3_LMP_IDMA0_BUS_ERROR 9
#define ISP_FE_FC_BAYER_CTX3_LMP_IDMA1_BUS_ERROR 10

#define ISP_FE_FC_BAYER_CTX4_BASE {HW_EVENT_MASK + 128}

#define ISP_FE_FC_BAYER_CTX4_FC_SOF 0
#define ISP_FE_FC_BAYER_CTX4_FC_EOF 1
#define ISP_FE_FC_BAYER_CTX4_FC_REG_UPDATED 2
#define ISP_FE_FC_BAYER_CTX4_FC_ABORT_START 3
#define ISP_FE_FC_BAYER_CTX4_FC_ABORT_DMA_CMPLT 4
#define ISP_FE_FC_BAYER_CTX4_FC_ABORT_DONE 5
#define ISP_FE_FC_BAYER_CTX4_FC_LATE_CONFIG 6
#define ISP_FE_FC_BAYER_CTX4_FC_ERROR 7
#define ISP_FE_FC_BAYER_CTX4_SPD_WDMA_BUS_ERROR 8
#define ISP_FE_FC_BAYER_CTX4_LMP_IDMA0_BUS_ERROR 9
#define ISP_FE_FC_BAYER_CTX4_LMP_IDMA1_BUS_ERROR 10

#define ISP_FE_FC_PDAF_CTX0_BASE {HW_EVENT_MASK + 160}

#define ISP_FE_FC_PDAF_CTX0_PDAF_LATE_CONFIG 0
#define ISP_FE_FC_PDAF_CTX0_PDAF_ERROR 1

#define ISP_FE_FC_PDAF_CTX1_BASE {HW_EVENT_MASK + 192}

#define ISP_FE_FC_PDAF_CTX1_PDAF_LATE_CONFIG 0
#define ISP_FE_FC_PDAF_CTX1_PDAF_ERROR 1

#define ISP_FE_FC_PDAF_CTX2_BASE {HW_EVENT_MASK + 224}

#define ISP_FE_FC_PDAF_CTX2_PDAF_LATE_CONFIG 0
#define ISP_FE_FC_PDAF_CTX2_PDAF_ERROR 1

#define ISP_FE_FC_PDAF_CTX3_BASE {HW_EVENT_MASK + 256}

#define ISP_FE_FC_PDAF_CTX3_PDAF_LATE_CONFIG 0
#define ISP_FE_FC_PDAF_CTX3_PDAF_ERROR 1

/* clang-format on */

#define LWIS_PLATFORM_EVENT_ID_ISP_FE_CTX0_FC_SOF \
	EVENT_ID(ISP_FE_FC_BAYER_CTX0_BASE, \
					 ISP_FE_FC_BAYER_CTX0_FC_SOF)
#define LWIS_PLATFORM_EVENT_ID_ISP_FE_CTX0_FC_EOF \
	EVENT_ID(ISP_FE_FC_BAYER_CTX0_BASE, \
					 ISP_FE_FC_BAYER_CTX0_FC_EOF)
#define LWIS_PLATFORM_EVENT_ID_ISP_FE_CTX0_FC_REG_UPDATED \
	EVENT_ID(ISP_FE_FC_BAYER_CTX0_BASE, \
					 ISP_FE_FC_BAYER_CTX0_FC_REG_UPDATED)
#define LWIS_PLATFORM_EVENT_ID_ISP_FE_CTX0_FC_ABORT_START \
	EVENT_ID(ISP_FE_FC_BAYER_CTX0_BASE, \
					 ISP_FE_FC_BAYER_CTX0_FC_ABORT_START)
#define LWIS_PLATFORM_EVENT_ID_ISP_FE_CTX0_FC_ABORT_DMA_CMPLT \
	EVENT_ID(ISP_FE_FC_BAYER_CTX0_BASE, \
					 ISP_FE_FC_BAYER_CTX0_FC_ABORT_DMA_CMPLT)
#define LWIS_PLATFORM_EVENT_ID_ISP_FE_CTX0_FC_ABORT_DONE \
	EVENT_ID(ISP_FE_FC_BAYER_CTX0_BASE, \
					 ISP_FE_FC_BAYER_CTX0_FC_ABORT_DONE)
#define LWIS_PLATFORM_EVENT_ID_ISP_FE_CTX0_FC_LATE_CONFIG \
	EVENT_ID(ISP_FE_FC_BAYER_CTX0_BASE, \
					 ISP_FE_FC_BAYER_CTX0_FC_LATE_CONFIG)
#define LWIS_PLATFORM_EVENT_ID_ISP_FE_CTX0_FC_ERROR \
	EVENT_ID(ISP_FE_FC_BAYER_CTX0_BASE, \
					 ISP_FE_FC_BAYER_CTX0_FC_ERROR)
#define LWIS_PLATFORM_EVENT_ID_ISP_FE_CTX0_SPD_WDMA_BUS_ERROR \
	EVENT_ID(ISP_FE_FC_BAYER_CTX0_BASE, \
					 ISP_FE_FC_BAYER_CTX0_SPD_WDMA_BUS_ERROR)
#define LWIS_PLATFORM_EVENT_ID_ISP_FE_CTX0_LMP_IDMA0_BUS_ERROR \
	EVENT_ID(ISP_FE_FC_BAYER_CTX0_BASE, \
					 ISP_FE_FC_BAYER_CTX0_LMP_IDMA0_BUS_ERROR)
#define LWIS_PLATFORM_EVENT_ID_ISP_FE_CTX0_LMP_IDMA1_BUS_ERROR \
	EVENT_ID(ISP_FE_FC_BAYER_CTX0_BASE, \
					 ISP_FE_FC_BAYER_CTX0_LMP_IDMA1_BUS_ERROR)

#define LWIS_PLATFORM_EVENT_ID_ISP_FE_CTX1_FC_SOF \
	EVENT_ID(ISP_FE_FC_BAYER_CTX1_BASE, \
					 ISP_FE_FC_BAYER_CTX1_FC_SOF)
#define LWIS_PLATFORM_EVENT_ID_ISP_FE_CTX1_FC_EOF \
	EVENT_ID(ISP_FE_FC_BAYER_CTX1_BASE, \
					 ISP_FE_FC_BAYER_CTX1_FC_EOF)
#define LWIS_PLATFORM_EVENT_ID_ISP_FE_CTX1_FC_REG_UPDATED \
	EVENT_ID(ISP_FE_FC_BAYER_CTX1_BASE, \
					 ISP_FE_FC_BAYER_CTX1_FC_REG_UPDATED)
#define LWIS_PLATFORM_EVENT_ID_ISP_FE_CTX1_FC_ABORT_START \
	EVENT_ID(ISP_FE_FC_BAYER_CTX1_BASE, \
					 ISP_FE_FC_BAYER_CTX1_FC_ABORT_START)
#define LWIS_PLATFORM_EVENT_ID_ISP_FE_CTX1_FC_ABORT_DMA_CMPLT \
	EVENT_ID(ISP_FE_FC_BAYER_CTX1_BASE, \
					 ISP_FE_FC_BAYER_CTX1_FC_ABORT_DMA_CMPLT)
#define LWIS_PLATFORM_EVENT_ID_ISP_FE_CTX1_FC_ABORT_DONE \
	EVENT_ID(ISP_FE_FC_BAYER_CTX1_BASE, \
					 ISP_FE_FC_BAYER_CTX1_FC_ABORT_DONE)
#define LWIS_PLATFORM_EVENT_ID_ISP_FE_CTX1_FC_LATE_CONFIG \
	EVENT_ID(ISP_FE_FC_BAYER_CTX1_BASE, \
					 ISP_FE_FC_BAYER_CTX1_FC_LATE_CONFIG)
#define LWIS_PLATFORM_EVENT_ID_ISP_FE_CTX1_FC_ERROR \
	EVENT_ID(ISP_FE_FC_BAYER_CTX1_BASE, \
					 ISP_FE_FC_BAYER_CTX1_FC_ERROR)
#define LWIS_PLATFORM_EVENT_ID_ISP_FE_CTX1_SPD_WDMA_BUS_ERROR \
	EVENT_ID(ISP_FE_FC_BAYER_CTX1_BASE, \
					 ISP_FE_FC_BAYER_CTX1_SPD_WDMA_BUS_ERROR)
#define LWIS_PLATFORM_EVENT_ID_ISP_FE_CTX1_LMP_IDMA0_BUS_ERROR \
	EVENT_ID(ISP_FE_FC_BAYER_CTX1_BASE, \
					 ISP_FE_FC_BAYER_CTX1_LMP_IDMA0_BUS_ERROR)
#define LWIS_PLATFORM_EVENT_ID_ISP_FE_CTX1_LMP_IDMA1_BUS_ERROR \
	EVENT_ID(ISP_FE_FC_BAYER_CTX1_BASE, \
					 ISP_FE_FC_BAYER_CTX1_LMP_IDMA1_BUS_ERROR)

#define LWIS_PLATFORM_EVENT_ID_ISP_FE_CTX2_FC_SOF \
	EVENT_ID(ISP_FE_FC_BAYER_CTX2_BASE, \
					 ISP_FE_FC_BAYER_CTX2_FC_SOF)
#define LWIS_PLATFORM_EVENT_ID_ISP_FE_CTX2_FC_EOF \
	EVENT_ID(ISP_FE_FC_BAYER_CTX2_BASE, \
					 ISP_FE_FC_BAYER_CTX2_FC_EOF)
#define LWIS_PLATFORM_EVENT_ID_ISP_FE_CTX2_FC_REG_UPDATED \
	EVENT_ID(ISP_FE_FC_BAYER_CTX2_BASE, \
					 ISP_FE_FC_BAYER_CTX2_FC_REG_UPDATED)
#define LWIS_PLATFORM_EVENT_ID_ISP_FE_CTX2_FC_ABORT_START \
	EVENT_ID(ISP_FE_FC_BAYER_CTX2_BASE, \
					 ISP_FE_FC_BAYER_CTX2_FC_ABORT_START)
#define LWIS_PLATFORM_EVENT_ID_ISP_FE_CTX2_FC_ABORT_DMA_CMPLT \
	EVENT_ID(ISP_FE_FC_BAYER_CTX2_BASE, \
					 ISP_FE_FC_BAYER_CTX2_FC_ABORT_DMA_CMPLT)
#define LWIS_PLATFORM_EVENT_ID_ISP_FE_CTX2_FC_ABORT_DONE \
	EVENT_ID(ISP_FE_FC_BAYER_CTX2_BASE, \
					 ISP_FE_FC_BAYER_CTX2_FC_ABORT_DONE)
#define LWIS_PLATFORM_EVENT_ID_ISP_FE_CTX2_FC_LATE_CONFIG \
	EVENT_ID(ISP_FE_FC_BAYER_CTX2_BASE, \
					 ISP_FE_FC_BAYER_CTX2_FC_LATE_CONFIG)
#define LWIS_PLATFORM_EVENT_ID_ISP_FE_CTX2_FC_ERROR \
	EVENT_ID(ISP_FE_FC_BAYER_CTX2_BASE, \
					 ISP_FE_FC_BAYER_CTX2_FC_ERROR)
#define LWIS_PLATFORM_EVENT_ID_ISP_FE_CTX2_SPD_WDMA_BUS_ERROR \
	EVENT_ID(ISP_FE_FC_BAYER_CTX2_BASE, \
					 ISP_FE_FC_BAYER_CTX2_SPD_WDMA_BUS_ERROR)
#define LWIS_PLATFORM_EVENT_ID_ISP_FE_CTX2_LMP_IDMA0_BUS_ERROR \
	EVENT_ID(ISP_FE_FC_BAYER_CTX2_BASE, \
					 ISP_FE_FC_BAYER_CTX2_LMP_IDMA0_BUS_ERROR)
#define LWIS_PLATFORM_EVENT_ID_ISP_FE_CTX2_LMP_IDMA1_BUS_ERROR \
	EVENT_ID(ISP_FE_FC_BAYER_CTX2_BASE, \
					 ISP_FE_FC_BAYER_CTX2_LMP_IDMA1_BUS_ERROR)

#define LWIS_PLATFORM_EVENT_ID_ISP_FE_CTX3_FC_SOF \
	EVENT_ID(ISP_FE_FC_BAYER_CTX3_BASE, \
					 ISP_FE_FC_BAYER_CTX3_FC_SOF)
#define LWIS_PLATFORM_EVENT_ID_ISP_FE_CTX3_FC_EOF \
	EVENT_ID(ISP_FE_FC_BAYER_CTX3_BASE, \
					 ISP_FE_FC_BAYER_CTX3_FC_EOF)
#define LWIS_PLATFORM_EVENT_ID_ISP_FE_CTX3_FC_REG_UPDATED \
	EVENT_ID(ISP_FE_FC_BAYER_CTX3_BASE, \
					 ISP_FE_FC_BAYER_CTX3_FC_REG_UPDATED)
#define LWIS_PLATFORM_EVENT_ID_ISP_FE_CTX3_FC_ABORT_START \
	EVENT_ID(ISP_FE_FC_BAYER_CTX3_BASE, \
					 ISP_FE_FC_BAYER_CTX3_FC_ABORT_START)
#define LWIS_PLATFORM_EVENT_ID_ISP_FE_CTX3_FC_ABORT_DMA_CMPLT \
	EVENT_ID(ISP_FE_FC_BAYER_CTX3_BASE, \
					 ISP_FE_FC_BAYER_CTX3_FC_ABORT_DMA_CMPLT)
#define LWIS_PLATFORM_EVENT_ID_ISP_FE_CTX3_FC_ABORT_DONE \
	EVENT_ID(ISP_FE_FC_BAYER_CTX3_BASE, \
					 ISP_FE_FC_BAYER_CTX3_FC_ABORT_DONE)
#define LWIS_PLATFORM_EVENT_ID_ISP_FE_CTX3_FC_LATE_CONFIG \
	EVENT_ID(ISP_FE_FC_BAYER_CTX3_BASE, \
					 ISP_FE_FC_BAYER_CTX3_FC_LATE_CONFIG)
#define LWIS_PLATFORM_EVENT_ID_ISP_FE_CTX3_FC_ERROR \
	EVENT_ID(ISP_FE_FC_BAYER_CTX3_BASE, \
					 ISP_FE_FC_BAYER_CTX3_FC_ERROR)
#define LWIS_PLATFORM_EVENT_ID_ISP_FE_CTX3_SPD_WDMA_BUS_ERROR \
	EVENT_ID(ISP_FE_FC_BAYER_CTX3_BASE, \
					 ISP_FE_FC_BAYER_CTX3_SPD_WDMA_BUS_ERROR)
#define LWIS_PLATFORM_EVENT_ID_ISP_FE_CTX3_LMP_IDMA0_BUS_ERROR \
	EVENT_ID(ISP_FE_FC_BAYER_CTX3_BASE, \
					 ISP_FE_FC_BAYER_CTX3_LMP_IDMA0_BUS_ERROR)
#define LWIS_PLATFORM_EVENT_ID_ISP_FE_CTX3_LMP_IDMA1_BUS_ERROR \
	EVENT_ID(ISP_FE_FC_BAYER_CTX3_BASE, \
					 ISP_FE_FC_BAYER_CTX3_LMP_IDMA1_BUS_ERROR)

#define LWIS_PLATFORM_EVENT_ID_ISP_FE_CTX4_FC_SOF \
	EVENT_ID(ISP_FE_FC_BAYER_CTX4_BASE, \
					 ISP_FE_FC_BAYER_CTX4_FC_SOF)
#define LWIS_PLATFORM_EVENT_ID_ISP_FE_CTX4_FC_EOF \
	EVENT_ID(ISP_FE_FC_BAYER_CTX4_BASE, \
					 ISP_FE_FC_BAYER_CTX4_FC_EOF)
#define LWIS_PLATFORM_EVENT_ID_ISP_FE_CTX4_FC_REG_UPDATED \
	EVENT_ID(ISP_FE_FC_BAYER_CTX4_BASE, \
					 ISP_FE_FC_BAYER_CTX4_FC_REG_UPDATED)
#define LWIS_PLATFORM_EVENT_ID_ISP_FE_CTX4_FC_ABORT_START \
	EVENT_ID(ISP_FE_FC_BAYER_CTX4_BASE, \
					 ISP_FE_FC_BAYER_CTX4_FC_ABORT_START)
#define LWIS_PLATFORM_EVENT_ID_ISP_FE_CTX4_FC_ABORT_DMA_CMPLT \
	EVENT_ID(ISP_FE_FC_BAYER_CTX4_BASE, \
					 ISP_FE_FC_BAYER_CTX4_FC_ABORT_DMA_CMPLT)
#define LWIS_PLATFORM_EVENT_ID_ISP_FE_CTX4_FC_ABORT_DONE \
	EVENT_ID(ISP_FE_FC_BAYER_CTX4_BASE, \
					 ISP_FE_FC_BAYER_CTX4_FC_ABORT_DONE)
#define LWIS_PLATFORM_EVENT_ID_ISP_FE_CTX4_FC_LATE_CONFIG \
	EVENT_ID(ISP_FE_FC_BAYER_CTX4_BASE, \
					 ISP_FE_FC_BAYER_CTX4_FC_LATE_CONFIG)
#define LWIS_PLATFORM_EVENT_ID_ISP_FE_CTX4_FC_ERROR \
	EVENT_ID(ISP_FE_FC_BAYER_CTX4_BASE, \
					 ISP_FE_FC_BAYER_CTX4_FC_ERROR)
#define LWIS_PLATFORM_EVENT_ID_ISP_FE_CTX4_SPD_WDMA_BUS_ERROR \
	EVENT_ID(ISP_FE_FC_BAYER_CTX4_BASE, \
					 ISP_FE_FC_BAYER_CTX4_SPD_WDMA_BUS_ERROR)
#define LWIS_PLATFORM_EVENT_ID_ISP_FE_CTX4_LMP_IDMA0_BUS_ERROR \
	EVENT_ID(ISP_FE_FC_BAYER_CTX4_BASE, \
					 ISP_FE_FC_BAYER_CTX4_LMP_IDMA0_BUS_ERROR)
#define LWIS_PLATFORM_EVENT_ID_ISP_FE_CTX4_LMP_IDMA1_BUS_ERROR \
	EVENT_ID(ISP_FE_FC_BAYER_CTX4_BASE, \
					 ISP_FE_FC_BAYER_CTX4_LMP_IDMA1_BUS_ERROR)

#define LWIS_PLATFORM_EVENT_ID_ISP_FE_CTX0_PDAF_LATE_CONFIG \
	EVENT_ID(ISP_FE_FC_PDAF_CTX0_BASE, \
					 ISP_FE_FC_PDAF_CTX0_PDAF_LATE_CONFIG)
#define LWIS_PLATFORM_EVENT_ID_ISP_FE_CTX0_PDAF_ERROR \
	EVENT_ID(ISP_FE_FC_PDAF_CTX0_BASE, \
					 ISP_FE_FC_PDAF_CTX0_PDAF_ERROR)

#define LWIS_PLATFORM_EVENT_ID_ISP_FE_CTX1_PDAF_LATE_CONFIG \
	EVENT_ID(ISP_FE_FC_PDAF_CTX1_BASE, \
					 ISP_FE_FC_PDAF_CTX1_PDAF_LATE_CONFIG)
#define LWIS_PLATFORM_EVENT_ID_ISP_FE_CTX1_PDAF_ERROR \
	EVENT_ID(ISP_FE_FC_PDAF_CTX1_BASE, \
					 ISP_FE_FC_PDAF_CTX1_PDAF_ERROR)

#define LWIS_PLATFORM_EVENT_ID_ISP_FE_CTX2_PDAF_LATE_CONFIG \
	EVENT_ID(ISP_FE_FC_PDAF_CTX2_BASE, \
					 ISP_FE_FC_PDAF_CTX2_PDAF_LATE_CONFIG)
#define LWIS_PLATFORM_EVENT_ID_ISP_FE_CTX2_PDAF_ERROR \
	EVENT_ID(ISP_FE_FC_PDAF_CTX2_BASE, \
					 ISP_FE_FC_PDAF_CTX2_PDAF_ERROR)

#define LWIS_PLATFORM_EVENT_ID_ISP_FE_CTX3_PDAF_LATE_CONFIG \
	EVENT_ID(ISP_FE_FC_PDAF_CTX3_BASE, \
					 ISP_FE_FC_PDAF_CTX3_PDAF_LATE_CONFIG)
#define LWIS_PLATFORM_EVENT_ID_ISP_FE_CTX3_PDAF_ERROR \
	EVENT_ID(ISP_FE_FC_PDAF_CTX3_BASE, \
					 ISP_FE_FC_PDAF_CTX3_PDAF_ERROR)

#endif /* DT_BINDINGS_LWIS_PLATFORM_ZUMA_ISP_FE_H_ */
