/* SPDX-License-Identifier: GPL-2.0-only */
/*
 * Google LWIS ZUMA ISP_FE Interrupt And Event Defines
 *
 * Copyright (c) 2022 Google, LLC
 */

#ifndef DT_BINDINGS_LWIS_PLATFORM_ZUMA_ISP_FE_H_
#define DT_BINDINGS_LWIS_PLATFORM_ZUMA_ISP_FE_H_

#include <dt-bindings/lwis/platform/common.h>

/* clang-format off */

#define ISP_FE_FC_BAYER_CTX0_BASE {HW_EVENT_MASK + 0}

#define ISP_FE_FC_BAYER_CTX0_FC_SOF 0
#define ISP_FE_FC_BAYER_CTX0_FC_EOF 1
#define ISP_FE_FC_BAYER_CTX0_FC_REG_UPDATED 2
#define ISP_FE_FC_BAYER_CTX0_FC_ABORT_START 3
#define ISP_FE_FC_BAYER_CTX0_FC_ABORT_DMA_CMPLT 4
#define ISP_FE_FC_BAYER_CTX0_FC_ABORT_DONE 5
#define ISP_FE_FC_BAYER_CTX0_FC_LATE_CONFIG 6
#define ISP_FE_FC_BAYER_CTX0_FC_ERROR 7
#define ISP_FE_FC_BAYER_CTX0_SPD_WDMA_BUS_ERROR 8
#define ISP_FE_FC_BAYER_CTX0_LMP_IDMA0_BUS_ERROR 9
#define ISP_FE_FC_BAYER_CTX0_LMP_IDMA1_BUS_ERROR 10

#define ISP_FE_FC_BAYER_CTX1_BASE {HW_EVENT_MASK + 32}

#define ISP_FE_FC_BAYER_CTX1_FC_SOF 0
#define ISP_FE_FC_BAYER_CTX1_FC_EOF 1
#define ISP_FE_FC_BAYER_CTX1_FC_REG_UPDATED 2
#define ISP_FE_FC_BAYER_CTX1_FC_ABORT_START 3
#define ISP_FE_FC_BAYER_CTX1_FC_ABORT_DMA_CMPLT 4
#define ISP_FE_FC_BAYER_CTX1_FC_ABORT_DONE 5
#define ISP_FE_FC_BAYER_CTX1_FC_LATE_CONFIG 6
#define ISP_FE_FC_BAYER_CTX1_FC_ERROR 7
#define ISP_FE_FC_BAYER_CTX1_SPD_WDMA_BUS_ERROR 8
#define ISP_FE_FC_BAYER_CTX1_LMP_IDMA0_BUS_ERROR 9
#define ISP_FE_FC_BAYER_CTX1_LMP_IDMA1_BUS_ERROR 10

#define ISP_FE_FC_BAYER_CTX2_BASE {HW_EVENT_MASK + 64}

#define ISP_FE_FC_BAYER_CTX2_FC_SOF 0
#define ISP_FE_FC_BAYER_CTX2_FC_EOF 1
#define ISP_FE_FC_BAYER_CTX2_FC_REG_UPDATED 2
#define ISP_FE_FC_BAYER_CTX2_FC_ABORT_START 3
#define ISP_FE_FC_BAYER_CTX2_FC_ABORT_DMA_CMPLT 4
#define ISP_FE_FC_BAYER_CTX2_FC_ABORT_DONE 5
#define ISP_FE_FC_BAYER_CTX2_FC_LATE_CONFIG 6
#define ISP_FE_FC_BAYER_CTX2_FC_ERROR 7
#define ISP_FE_FC_BAYER_CTX2_SPD_WDMA_BUS_ERROR 8
#define ISP_FE_FC_BAYER_CTX2_LMP_IDMA0_BUS_ERROR 9
#define ISP_FE_FC_BAYER_CTX2_LMP_IDMA1_BUS_ERROR 10

#define ISP_FE_FC_BAYER_CTX3_BASE {HW_EVENT_MASK + 96}

#define ISP_FE_FC_BAYER_CTX3_FC_SOF 0
#define ISP_FE_FC_BAYER_CTX3_FC_EOF 1
#define ISP_FE_FC_BAYER_CTX3_FC_REG_UPDATED 2
#define ISP_FE_FC_BAYER_CTX3_FC_ABORT_START 3
#define ISP_FE_FC_BAYER_CTX3_FC_ABORT_DMA_CMPLT 4
#define ISP_FE_FC_BAYER_CTX3_FC_ABORT_DONE 5
#define ISP_FE_FC_BAYER_CTX3_FC_LATE_CONFIG 6
#define ISP_FE_FC_BAYER_CTX3_FC_ERROR 7
#define ISP_FE_FC_BAYER_CTX3_SPD_WDMA_BUS_ERROR 8
#define ISP_FE_FC_BAYER_CTX3_LMP_IDMA0_BUS_ERROR 9
#define ISP_FE_FC_BAYER_CTX3_LMP_IDMA1_BUS_ERROR 10

#define ISP_FE_FC_BAYER_CTX4_BASE {HW_EVENT_MASK + 128}

#define ISP_FE_FC_BAYER_CTX4_FC_SOF 0
#define ISP_FE_FC_BAYER_CTX4_FC_EOF 1
#define ISP_FE_FC_BAYER_CTX4_FC_REG_UPDATED 2
#define ISP_FE_FC_BAYER_CTX4_FC_ABORT_START 3
#define ISP_FE_FC_BAYER_CTX4_FC_ABORT_DMA_CMPLT 4
#define ISP_FE_FC_BAYER_CTX4_FC_ABORT_DONE 5
#define ISP_FE_FC_BAYER_CTX4_FC_LATE_CONFIG 6
#define ISP_FE_FC_BAYER_CTX4_FC_ERROR 7
#define ISP_FE_FC_BAYER_CTX4_SPD_WDMA_BUS_ERROR 8
#define ISP_FE_FC_BAYER_CTX4_LMP_IDMA0_BUS_ERROR 9
#define ISP_FE_FC_BAYER_CTX4_LMP_IDMA1_BUS_ERROR 10

#define ISP_FE_FC_PDAF_CTX0_BASE {HW_EVENT_MASK + 160}

#define ISP_FE_FC_PDAF_CTX0_PDAF_LATE_CONFIG 0
#define ISP_FE_FC_PDAF_CTX0_PDAF_ERROR 1

#define ISP_FE_FC_PDAF_CTX1_BASE {HW_EVENT_MASK + 192}

#define ISP_FE_FC_PDAF_CTX1_PDAF_LATE_CONFIG 0
#define ISP_FE_FC_PDAF_CTX1_PDAF_ERROR 1

#define ISP_FE_FC_PDAF_CTX2_BASE {HW_EVENT_MASK + 224}

#define ISP_FE_FC_PDAF_CTX2_PDAF_LATE_CONFIG 0
#define ISP_FE_FC_PDAF_CTX2_PDAF_ERROR 1

#define ISP_FE_FC_PDAF_CTX3_BASE {HW_EVENT_MASK + 256}

#define ISP_FE_FC_PDAF_CTX3_PDAF_LATE_CONFIG 0
#define ISP_FE_FC_PDAF_CTX3_PDAF_ERROR 1

#define ISP_FE_PDMA_CTX0_BASE {HW_EVENT_MASK + 288}

#define ISP_FE_PDMA_CTX0_IRQ_CMD 0
#define ISP_FE_PDMA_CTX0_ALMOST_EMPTY 1

#define ISP_FE_PDMA_CTX1_BASE {HW_EVENT_MASK + 320}

#define ISP_FE_PDMA_CTX1_IRQ_CMD 0
#define ISP_FE_PDMA_CTX1_ALMOST_EMPTY 1

#define ISP_FE_PDMA_CTX2_BASE {HW_EVENT_MASK + 352}

#define ISP_FE_PDMA_CTX2_IRQ_CMD 0
#define ISP_FE_PDMA_CTX2_ALMOST_EMPTY 1

#define ISP_FE_PDMA_CTX3_BASE {HW_EVENT_MASK + 384}

#define ISP_FE_PDMA_CTX3_IRQ_CMD 0
#define ISP_FE_PDMA_CTX3_ALMOST_EMPTY 1

#define ISP_FE_PDMA_CTX4_BASE {HW_EVENT_MASK + 416}

#define ISP_FE_PDMA_CTX4_IRQ_CMD 0
#define ISP_FE_PDMA_CTX4_ALMOST_EMPTY 1

#define ISP_FE_PDMA_ERR_CTX0_BASE {HW_EVENT_MASK + 448}

#define ISP_FE_PDMA_ERR_CTX0_MEM_BUS_ERR 0
#define ISP_FE_PDMA_ERR_CTX0_CSR_BUS_ERR 1
#define ISP_FE_PDMA_ERR_CTX0_ILLEGAL_CMD 2
#define ISP_FE_PDMA_ERR_CTX0_RECUR_INDIR_CMD 3
#define ISP_FE_PDMA_ERR_CTX0_CMD_SIZE_MISMATCH 4

#define ISP_FE_PDMA_ERR_CTX1_BASE {HW_EVENT_MASK + 480}

#define ISP_FE_PDMA_ERR_CTX1_MEM_BUS_ERR 0
#define ISP_FE_PDMA_ERR_CTX1_CSR_BUS_ERR 1
#define ISP_FE_PDMA_ERR_CTX1_ILLEGAL_CMD 2
#define ISP_FE_PDMA_ERR_CTX1_RECUR_INDIR_CMD 3
#define ISP_FE_PDMA_ERR_CTX1_CMD_SIZE_MISMATCH 4

#define ISP_FE_PDMA_ERR_CTX2_BASE {HW_EVENT_MASK + 512}

#define ISP_FE_PDMA_ERR_CTX2_MEM_BUS_ERR 0
#define ISP_FE_PDMA_ERR_CTX2_CSR_BUS_ERR 1
#define ISP_FE_PDMA_ERR_CTX2_ILLEGAL_CMD 2
#define ISP_FE_PDMA_ERR_CTX2_RECUR_INDIR_CMD 3
#define ISP_FE_PDMA_ERR_CTX2_CMD_SIZE_MISMATCH 4

#define ISP_FE_PDMA_ERR_CTX3_BASE {HW_EVENT_MASK + 544}

#define ISP_FE_PDMA_ERR_CTX3_MEM_BUS_ERR 0
#define ISP_FE_PDMA_ERR_CTX3_CSR_BUS_ERR 1
#define ISP_FE_PDMA_ERR_CTX3_ILLEGAL_CMD 2
#define ISP_FE_PDMA_ERR_CTX3_RECUR_INDIR_CMD 3
#define ISP_FE_PDMA_ERR_CTX3_CMD_SIZE_MISMATCH 4

#define ISP_FE_PDMA_ERR_CTX4_BASE {HW_EVENT_MASK + 576}

#define ISP_FE_PDMA_ERR_CTX4_MEM_BUS_ERR 0
#define ISP_FE_PDMA_ERR_CTX4_CSR_BUS_ERR 1
#define ISP_FE_PDMA_ERR_CTX4_ILLEGAL_CMD 2
#define ISP_FE_PDMA_ERR_CTX4_RECUR_INDIR_CMD 3
#define ISP_FE_PDMA_ERR_CTX4_CMD_SIZE_MISMATCH 4

#define ISP_FE_PDMA_RSTCTL_CTX0_BASE {HW_EVENT_MASK + 608}

#define ISP_FE_PDMA_RSTCTL_CTX0_SW_RESET_DONE 0
#define ISP_FE_PDMA_RSTCTL_CTX0_INPUT_FLUSH_DONE 1
#define ISP_FE_PDMA_RSTCTL_CTX0_SW_MODE 2
#define ISP_FE_PDMA_RSTCTL_CTX0_APB_GKP_ERR 3
#define ISP_FE_PDMA_RSTCTL_CTX0_AXI_GKP_ERR 4

#define ISP_FE_PDMA_RSTCTL_CTX1_BASE {HW_EVENT_MASK + 640}

#define ISP_FE_PDMA_RSTCTL_CTX1_SW_RESET_DONE 0
#define ISP_FE_PDMA_RSTCTL_CTX1_INPUT_FLUSH_DONE 1
#define ISP_FE_PDMA_RSTCTL_CTX1_SW_MODE 2
#define ISP_FE_PDMA_RSTCTL_CTX1_APB_GKP_ERR 3
#define ISP_FE_PDMA_RSTCTL_CTX1_AXI_GKP_ERR 4

#define ISP_FE_PDMA_RSTCTL_CTX2_BASE {HW_EVENT_MASK + 672}

#define ISP_FE_PDMA_RSTCTL_CTX2_SW_RESET_DONE 0
#define ISP_FE_PDMA_RSTCTL_CTX2_INPUT_FLUSH_DONE 1
#define ISP_FE_PDMA_RSTCTL_CTX2_SW_MODE 2
#define ISP_FE_PDMA_RSTCTL_CTX2_APB_GKP_ERR 3
#define ISP_FE_PDMA_RSTCTL_CTX2_AXI_GKP_ERR 4

#define ISP_FE_PDMA_RSTCTL_CTX3_BASE {HW_EVENT_MASK + 704}

#define ISP_FE_PDMA_RSTCTL_CTX3_SW_RESET_DONE 0
#define ISP_FE_PDMA_RSTCTL_CTX3_INPUT_FLUSH_DONE 1
#define ISP_FE_PDMA_RSTCTL_CTX3_SW_MODE 2
#define ISP_FE_PDMA_RSTCTL_CTX3_APB_GKP_ERR 3
#define ISP_FE_PDMA_RSTCTL_CTX3_AXI_GKP_ERR 4

#define ISP_FE_PDMA_RSTCTL_CTX4_BASE {HW_EVENT_MASK + 736}

#define ISP_FE_PDMA_RSTCTL_CTX4_SW_RESET_DONE 0
#define ISP_FE_PDMA_RSTCTL_CTX4_INPUT_FLUSH_DONE 1
#define ISP_FE_PDMA_RSTCTL_CTX4_SW_MODE 2
#define ISP_FE_PDMA_RSTCTL_CTX4_APB_GKP_ERR 3
#define ISP_FE_PDMA_RSTCTL_CTX4_AXI_GKP_ERR 4

#define ISP_FE_LMP_BAYER_CTX0_BASE {HW_EVENT_MASK + 768}

#define ISP_FE_LMP_BAYER_CTX0_REGISTER_UPDATE 0
#define ISP_FE_LMP_BAYER_CTX0_EOF 1
#define ISP_FE_LMP_BAYER_CTX0_END_OF_BATCH 2
#define ISP_FE_LMP_BAYER_CTX0_FE_LMP_ERROR 3
#define ISP_FE_LMP_BAYER_CTX0_CDAF_PRIMARY 4
#define ISP_FE_LMP_BAYER_CTX0_CDAF_WINDOWS 5
#define ISP_FE_LMP_BAYER_CTX0_PRE_LSC_AE_STATS 6
#define ISP_FE_LMP_BAYER_CTX0_AWB_STATS 7
#define ISP_FE_LMP_BAYER_CTX0_LSC_STATS 8
#define ISP_FE_LMP_BAYER_CTX0_FLICKER_STATS 9
#define ISP_FE_LMP_BAYER_CTX0_HISTOGRAM0 10
#define ISP_FE_LMP_BAYER_CTX0_HISTOGRAM1 11
#define ISP_FE_LMP_BAYER_CTX0_HISTOGRAM2 12
#define ISP_FE_LMP_BAYER_CTX0_POST_LSC_AE_STATS 13
#define ISP_FE_LMP_BAYER_CTX0_MOTION_METERING 14
#define ISP_FE_LMP_BAYER_CTX0_BAYER0_WDMA 15
#define ISP_FE_LMP_BAYER_CTX0_BAYER1_WDMA 16
#define ISP_FE_LMP_BAYER_CTX0_LINEAR_RGB_OUTPUT 17
#define ISP_FE_LMP_BAYER_CTX0_ML_OUTPUT0 18
#define ISP_FE_LMP_BAYER_CTX0_ML_OUTPUT1 19
#define ISP_FE_LMP_BAYER_CTX0_ML_OUTPUT2 20
#define ISP_FE_LMP_BAYER_CTX0_TNR_PYRAMID 21
#define ISP_FE_LMP_BAYER_CTX0_MERGE1 22
#define ISP_FE_LMP_BAYER_CTX0_MERGE2 23
#define ISP_FE_LMP_BAYER_CTX0_MERGE3 24
#define ISP_FE_LMP_BAYER_CTX0_MERGE4 25
#define ISP_FE_LMP_BAYER_CTX0_MERGE5 26
#define ISP_FE_LMP_BAYER_CTX0_MERGE6 27
#define ISP_FE_LMP_BAYER_CTX0_LMP_BUS_ERROR 28
#define ISP_FE_LMP_BAYER_CTX0_SOF 29

#define ISP_FE_LMP_BAYER_CTX1_BASE {HW_EVENT_MASK + 800}

#define ISP_FE_LMP_BAYER_CTX1_REGISTER_UPDATE 0
#define ISP_FE_LMP_BAYER_CTX1_EOF 1
#define ISP_FE_LMP_BAYER_CTX1_END_OF_BATCH 2
#define ISP_FE_LMP_BAYER_CTX1_FE_LMP_ERROR 3
#define ISP_FE_LMP_BAYER_CTX1_CDAF_PRIMARY 4
#define ISP_FE_LMP_BAYER_CTX1_CDAF_WINDOWS 5
#define ISP_FE_LMP_BAYER_CTX1_PRE_LSC_AE_STATS 6
#define ISP_FE_LMP_BAYER_CTX1_AWB_STATS 7
#define ISP_FE_LMP_BAYER_CTX1_LSC_STATS 8
#define ISP_FE_LMP_BAYER_CTX1_FLICKER_STATS 9
#define ISP_FE_LMP_BAYER_CTX1_HISTOGRAM0 10
#define ISP_FE_LMP_BAYER_CTX1_HISTOGRAM1 11
#define ISP_FE_LMP_BAYER_CTX1_HISTOGRAM2 12
#define ISP_FE_LMP_BAYER_CTX1_POST_LSC_AE_STATS 13
#define ISP_FE_LMP_BAYER_CTX1_MOTION_METERING 14
#define ISP_FE_LMP_BAYER_CTX1_BAYER0_WDMA 15
#define ISP_FE_LMP_BAYER_CTX1_BAYER1_WDMA 16
#define ISP_FE_LMP_BAYER_CTX1_LINEAR_RGB_OUTPUT 17
#define ISP_FE_LMP_BAYER_CTX1_ML_OUTPUT0 18
#define ISP_FE_LMP_BAYER_CTX1_ML_OUTPUT1 19
#define ISP_FE_LMP_BAYER_CTX1_ML_OUTPUT2 20
#define ISP_FE_LMP_BAYER_CTX1_TNR_PYRAMID 21
#define ISP_FE_LMP_BAYER_CTX1_MERGE1 22
#define ISP_FE_LMP_BAYER_CTX1_MERGE2 23
#define ISP_FE_LMP_BAYER_CTX1_MERGE3 24
#define ISP_FE_LMP_BAYER_CTX1_MERGE4 25
#define ISP_FE_LMP_BAYER_CTX1_MERGE5 26
#define ISP_FE_LMP_BAYER_CTX1_MERGE6 27
#define ISP_FE_LMP_BAYER_CTX1_LMP_BUS_ERROR 28
#define ISP_FE_LMP_BAYER_CTX1_SOF 29

#define ISP_FE_LMP_BAYER_CTX2_BASE {HW_EVENT_MASK + 832}

#define ISP_FE_LMP_BAYER_CTX2_REGISTER_UPDATE 0
#define ISP_FE_LMP_BAYER_CTX2_EOF 1
#define ISP_FE_LMP_BAYER_CTX2_END_OF_BATCH 2
#define ISP_FE_LMP_BAYER_CTX2_FE_LMP_ERROR 3
#define ISP_FE_LMP_BAYER_CTX2_CDAF_PRIMARY 4
#define ISP_FE_LMP_BAYER_CTX2_CDAF_WINDOWS 5
#define ISP_FE_LMP_BAYER_CTX2_PRE_LSC_AE_STATS 6
#define ISP_FE_LMP_BAYER_CTX2_AWB_STATS 7
#define ISP_FE_LMP_BAYER_CTX2_LSC_STATS 8
#define ISP_FE_LMP_BAYER_CTX2_FLICKER_STATS 9
#define ISP_FE_LMP_BAYER_CTX2_HISTOGRAM0 10
#define ISP_FE_LMP_BAYER_CTX2_HISTOGRAM1 11
#define ISP_FE_LMP_BAYER_CTX2_HISTOGRAM2 12
#define ISP_FE_LMP_BAYER_CTX2_POST_LSC_AE_STATS 13
#define ISP_FE_LMP_BAYER_CTX2_MOTION_METERING 14
#define ISP_FE_LMP_BAYER_CTX2_BAYER0_WDMA 15
#define ISP_FE_LMP_BAYER_CTX2_BAYER1_WDMA 16
#define ISP_FE_LMP_BAYER_CTX2_LINEAR_RGB_OUTPUT 17
#define ISP_FE_LMP_BAYER_CTX2_ML_OUTPUT0 18
#define ISP_FE_LMP_BAYER_CTX2_ML_OUTPUT1 19
#define ISP_FE_LMP_BAYER_CTX2_ML_OUTPUT2 20
#define ISP_FE_LMP_BAYER_CTX2_TNR_PYRAMID 21
#define ISP_FE_LMP_BAYER_CTX2_MERGE1 22
#define ISP_FE_LMP_BAYER_CTX2_MERGE2 23
#define ISP_FE_LMP_BAYER_CTX2_MERGE3 24
#define ISP_FE_LMP_BAYER_CTX2_MERGE4 25
#define ISP_FE_LMP_BAYER_CTX2_MERGE5 26
#define ISP_FE_LMP_BAYER_CTX2_MERGE6 27
#define ISP_FE_LMP_BAYER_CTX2_LMP_BUS_ERROR 28
#define ISP_FE_LMP_BAYER_CTX2_SOF 29

#define ISP_FE_LMP_BAYER_CTX3_BASE {HW_EVENT_MASK + 864}

#define ISP_FE_LMP_BAYER_CTX3_REGISTER_UPDATE 0
#define ISP_FE_LMP_BAYER_CTX3_EOF 1
#define ISP_FE_LMP_BAYER_CTX3_END_OF_BATCH 2
#define ISP_FE_LMP_BAYER_CTX3_FE_LMP_ERROR 3
#define ISP_FE_LMP_BAYER_CTX3_CDAF_PRIMARY 4
#define ISP_FE_LMP_BAYER_CTX3_CDAF_WINDOWS 5
#define ISP_FE_LMP_BAYER_CTX3_PRE_LSC_AE_STATS 6
#define ISP_FE_LMP_BAYER_CTX3_AWB_STATS 7
#define ISP_FE_LMP_BAYER_CTX3_LSC_STATS 8
#define ISP_FE_LMP_BAYER_CTX3_FLICKER_STATS 9
#define ISP_FE_LMP_BAYER_CTX3_HISTOGRAM0 10
#define ISP_FE_LMP_BAYER_CTX3_HISTOGRAM1 11
#define ISP_FE_LMP_BAYER_CTX3_HISTOGRAM2 12
#define ISP_FE_LMP_BAYER_CTX3_POST_LSC_AE_STATS 13
#define ISP_FE_LMP_BAYER_CTX3_MOTION_METERING 14
#define ISP_FE_LMP_BAYER_CTX3_BAYER0_WDMA 15
#define ISP_FE_LMP_BAYER_CTX3_BAYER1_WDMA 16
#define ISP_FE_LMP_BAYER_CTX3_LINEAR_RGB_OUTPUT 17
#define ISP_FE_LMP_BAYER_CTX3_ML_OUTPUT0 18
#define ISP_FE_LMP_BAYER_CTX3_ML_OUTPUT1 19
#define ISP_FE_LMP_BAYER_CTX3_ML_OUTPUT2 20
#define ISP_FE_LMP_BAYER_CTX3_TNR_PYRAMID 21
#define ISP_FE_LMP_BAYER_CTX3_MERGE1 22
#define ISP_FE_LMP_BAYER_CTX3_MERGE2 23
#define ISP_FE_LMP_BAYER_CTX3_MERGE3 24
#define ISP_FE_LMP_BAYER_CTX3_MERGE4 25
#define ISP_FE_LMP_BAYER_CTX3_MERGE5 26
#define ISP_FE_LMP_BAYER_CTX3_MERGE6 27
#define ISP_FE_LMP_BAYER_CTX3_LMP_BUS_ERROR 28
#define ISP_FE_LMP_BAYER_CTX3_SOF 29

#define ISP_FE_LMP_BAYER_CTX4_BASE {HW_EVENT_MASK + 896}

#define ISP_FE_LMP_BAYER_CTX4_REGISTER_UPDATE 0
#define ISP_FE_LMP_BAYER_CTX4_EOF 1
#define ISP_FE_LMP_BAYER_CTX4_END_OF_BATCH 2
#define ISP_FE_LMP_BAYER_CTX4_FE_LMP_ERROR 3
#define ISP_FE_LMP_BAYER_CTX4_CDAF_PRIMARY 4
#define ISP_FE_LMP_BAYER_CTX4_CDAF_WINDOWS 5
#define ISP_FE_LMP_BAYER_CTX4_PRE_LSC_AE_STATS 6
#define ISP_FE_LMP_BAYER_CTX4_AWB_STATS 7
#define ISP_FE_LMP_BAYER_CTX4_LSC_STATS 8
#define ISP_FE_LMP_BAYER_CTX4_FLICKER_STATS 9
#define ISP_FE_LMP_BAYER_CTX4_HISTOGRAM0 10
#define ISP_FE_LMP_BAYER_CTX4_HISTOGRAM1 11
#define ISP_FE_LMP_BAYER_CTX4_HISTOGRAM2 12
#define ISP_FE_LMP_BAYER_CTX4_POST_LSC_AE_STATS 13
#define ISP_FE_LMP_BAYER_CTX4_MOTION_METERING 14
#define ISP_FE_LMP_BAYER_CTX4_BAYER0_WDMA 15
#define ISP_FE_LMP_BAYER_CTX4_BAYER1_WDMA 16
#define ISP_FE_LMP_BAYER_CTX4_LINEAR_RGB_OUTPUT 17
#define ISP_FE_LMP_BAYER_CTX4_ML_OUTPUT0 18
#define ISP_FE_LMP_BAYER_CTX4_ML_OUTPUT1 19
#define ISP_FE_LMP_BAYER_CTX4_ML_OUTPUT2 20
#define ISP_FE_LMP_BAYER_CTX4_TNR_PYRAMID 21
#define ISP_FE_LMP_BAYER_CTX4_MERGE1 22
#define ISP_FE_LMP_BAYER_CTX4_MERGE2 23
#define ISP_FE_LMP_BAYER_CTX4_MERGE3 24
#define ISP_FE_LMP_BAYER_CTX4_MERGE4 25
#define ISP_FE_LMP_BAYER_CTX4_MERGE5 26
#define ISP_FE_LMP_BAYER_CTX4_MERGE6 27
#define ISP_FE_LMP_BAYER_CTX4_LMP_BUS_ERROR 28
#define ISP_FE_LMP_BAYER_CTX4_SOF 29

#define ISP_FE_LMP_PDAF_CTX0_BASE {HW_EVENT_MASK + 928}

#define ISP_FE_LMP_PDAF_CTX0_SOF 0
#define ISP_FE_LMP_PDAF_CTX0_EOF 1
#define ISP_FE_LMP_PDAF_CTX0_END_OF_BATCH 2
#define ISP_FE_LMP_PDAF_CTX0_EARLY 3
#define ISP_FE_LMP_PDAF_CTX0_REGISTER_UPDATE 4
#define ISP_FE_LMP_PDAF_CTX0_ABORT_START 5
#define ISP_FE_LMP_PDAF_CTX0_ABORT_DMA_COMPLETE 6
#define ISP_FE_LMP_PDAF_CTX0_ABORT_DONE 7
#define ISP_FE_LMP_PDAF_CTX0_ERROR 8
#define ISP_FE_LMP_PDAF_CTX0_BUS_ERROR 9

#define ISP_FE_LMP_PDAF_CTX1_BASE {HW_EVENT_MASK + 960}

#define ISP_FE_LMP_PDAF_CTX1_SOF 0
#define ISP_FE_LMP_PDAF_CTX1_EOF 1
#define ISP_FE_LMP_PDAF_CTX1_END_OF_BATCH 2
#define ISP_FE_LMP_PDAF_CTX1_EARLY 3
#define ISP_FE_LMP_PDAF_CTX1_REGISTER_UPDATE 4
#define ISP_FE_LMP_PDAF_CTX1_ABORT_START 5
#define ISP_FE_LMP_PDAF_CTX1_ABORT_DMA_COMPLETE 6
#define ISP_FE_LMP_PDAF_CTX1_ABORT_DONE 7
#define ISP_FE_LMP_PDAF_CTX1_ERROR 8
#define ISP_FE_LMP_PDAF_CTX1_BUS_ERROR 9

#define ISP_FE_LMP_PDAF_CTX2_BASE {HW_EVENT_MASK + 992}

#define ISP_FE_LMP_PDAF_CTX2_SOF 0
#define ISP_FE_LMP_PDAF_CTX2_EOF 1
#define ISP_FE_LMP_PDAF_CTX2_END_OF_BATCH 2
#define ISP_FE_LMP_PDAF_CTX2_EARLY 3
#define ISP_FE_LMP_PDAF_CTX2_REGISTER_UPDATE 4
#define ISP_FE_LMP_PDAF_CTX2_ABORT_START 5
#define ISP_FE_LMP_PDAF_CTX2_ABORT_DMA_COMPLETE 6
#define ISP_FE_LMP_PDAF_CTX2_ABORT_DONE 7
#define ISP_FE_LMP_PDAF_CTX2_ERROR 8
#define ISP_FE_LMP_PDAF_CTX2_BUS_ERROR 9

#define ISP_FE_LMP_PDAF_CTX3_BASE {HW_EVENT_MASK + 1024}

#define ISP_FE_LMP_PDAF_CTX3_SOF 0
#define ISP_FE_LMP_PDAF_CTX3_EOF 1
#define ISP_FE_LMP_PDAF_CTX3_END_OF_BATCH 2
#define ISP_FE_LMP_PDAF_CTX3_EARLY 3
#define ISP_FE_LMP_PDAF_CTX3_REGISTER_UPDATE 4
#define ISP_FE_LMP_PDAF_CTX3_ABORT_START 5
#define ISP_FE_LMP_PDAF_CTX3_ABORT_DMA_COMPLETE 6
#define ISP_FE_LMP_PDAF_CTX3_ABORT_DONE 7
#define ISP_FE_LMP_PDAF_CTX3_ERROR 8
#define ISP_FE_LMP_PDAF_CTX3_BUS_ERROR 9

#define ISP_FE_LMP_DEBUG_BASE {HW_EVENT_MASK + 1056}

#define ISP_FE_LMP_DEBUG_HW_TIMEOUT 0
#define ISP_FE_LMP_DEBUG_HW_BUS_ERROR 1
#define ISP_FE_LMP_DEBUG_HW_AXI_READ_DATA_OVERFLOW 2
#define ISP_FE_LMP_DEBUG_HW_AXI_WRITE_DATA_UNDERFLOW 3
#define ISP_FE_LMP_DEBUG_HW_LUT_ILLEGAL_PROGRAMMING_NON_SEQ 4
#define ISP_FE_LMP_DEBUG_HW_LUT_ILLEGAL_PROGRAMMING_NON_ATOMIC 5
#define ISP_FE_LMP_DEBUG_HW_LUT_ILLEGAL_PROGRAMMING_PARTIAL_BAYER 6
#define ISP_FE_LMP_DEBUG_HW_LUT_ILLEGAL_PROGRAMMING_PARTIAL_PDAF0 7
#define ISP_FE_LMP_DEBUG_HW_LUT_ILLEGAL_PROGRAMMING_PARTIAL_PDAF1 8
#define ISP_FE_LMP_DEBUG_HW_LUT_ILLEGAL_PROGRAMMING_PARTIAL_PDAF2 9
#define ISP_FE_LMP_DEBUG_HW_LUT_ILLEGAL_PROGRAMMING_PARTIAL_PDAF3 10
#define ISP_FE_LMP_DEBUG_HW_UNDEFINED 11

/* clang-format on */

#define LWIS_PLATFORM_EVENT_ID_ISP_FE_CTX0_FC_SOF \
	EVENT_ID(ISP_FE_FC_BAYER_CTX0_BASE, \
		 ISP_FE_FC_BAYER_CTX0_FC_SOF)
#define LWIS_PLATFORM_EVENT_ID_ISP_FE_CTX0_FC_EOF \
	EVENT_ID(ISP_FE_FC_BAYER_CTX0_BASE, \
		 ISP_FE_FC_BAYER_CTX0_FC_EOF)
#define LWIS_PLATFORM_EVENT_ID_ISP_FE_CTX0_FC_REG_UPDATED \
	EVENT_ID(ISP_FE_FC_BAYER_CTX0_BASE, \
		 ISP_FE_FC_BAYER_CTX0_FC_REG_UPDATED)
#define LWIS_PLATFORM_EVENT_ID_ISP_FE_CTX0_FC_ABORT_START \
	EVENT_ID(ISP_FE_FC_BAYER_CTX0_BASE, \
		 ISP_FE_FC_BAYER_CTX0_FC_ABORT_START)
#define LWIS_PLATFORM_EVENT_ID_ISP_FE_CTX0_FC_ABORT_DMA_CMPLT \
	EVENT_ID(ISP_FE_FC_BAYER_CTX0_BASE, \
		 ISP_FE_FC_BAYER_CTX0_FC_ABORT_DMA_CMPLT)
#define LWIS_PLATFORM_EVENT_ID_ISP_FE_CTX0_FC_ABORT_DONE \
	EVENT_ID(ISP_FE_FC_BAYER_CTX0_BASE, \
		 ISP_FE_FC_BAYER_CTX0_FC_ABORT_DONE)
#define LWIS_PLATFORM_EVENT_ID_ISP_FE_CTX0_FC_LATE_CONFIG \
	EVENT_ID(ISP_FE_FC_BAYER_CTX0_BASE, \
		 ISP_FE_FC_BAYER_CTX0_FC_LATE_CONFIG)
#define LWIS_PLATFORM_EVENT_ID_ISP_FE_CTX0_FC_ERROR \
	EVENT_ID(ISP_FE_FC_BAYER_CTX0_BASE, \
		 ISP_FE_FC_BAYER_CTX0_FC_ERROR)
#define LWIS_PLATFORM_EVENT_ID_ISP_FE_CTX0_SPD_WDMA_BUS_ERROR \
	EVENT_ID(ISP_FE_FC_BAYER_CTX0_BASE, \
		 ISP_FE_FC_BAYER_CTX0_SPD_WDMA_BUS_ERROR)
#define LWIS_PLATFORM_EVENT_ID_ISP_FE_CTX0_LMP_IDMA0_BUS_ERROR \
	EVENT_ID(ISP_FE_FC_BAYER_CTX0_BASE, \
		 ISP_FE_FC_BAYER_CTX0_LMP_IDMA0_BUS_ERROR)
#define LWIS_PLATFORM_EVENT_ID_ISP_FE_CTX0_LMP_IDMA1_BUS_ERROR \
	EVENT_ID(ISP_FE_FC_BAYER_CTX0_BASE, \
		 ISP_FE_FC_BAYER_CTX0_LMP_IDMA1_BUS_ERROR)

#define LWIS_PLATFORM_EVENT_ID_ISP_FE_CTX1_FC_SOF \
	EVENT_ID(ISP_FE_FC_BAYER_CTX1_BASE, \
		 ISP_FE_FC_BAYER_CTX1_FC_SOF)
#define LWIS_PLATFORM_EVENT_ID_ISP_FE_CTX1_FC_EOF \
	EVENT_ID(ISP_FE_FC_BAYER_CTX1_BASE, \
		 ISP_FE_FC_BAYER_CTX1_FC_EOF)
#define LWIS_PLATFORM_EVENT_ID_ISP_FE_CTX1_FC_REG_UPDATED \
	EVENT_ID(ISP_FE_FC_BAYER_CTX1_BASE, \
		 ISP_FE_FC_BAYER_CTX1_FC_REG_UPDATED)
#define LWIS_PLATFORM_EVENT_ID_ISP_FE_CTX1_FC_ABORT_START \
	EVENT_ID(ISP_FE_FC_BAYER_CTX1_BASE, \
		 ISP_FE_FC_BAYER_CTX1_FC_ABORT_START)
#define LWIS_PLATFORM_EVENT_ID_ISP_FE_CTX1_FC_ABORT_DMA_CMPLT \
	EVENT_ID(ISP_FE_FC_BAYER_CTX1_BASE, \
		 ISP_FE_FC_BAYER_CTX1_FC_ABORT_DMA_CMPLT)
#define LWIS_PLATFORM_EVENT_ID_ISP_FE_CTX1_FC_ABORT_DONE \
	EVENT_ID(ISP_FE_FC_BAYER_CTX1_BASE, \
		 ISP_FE_FC_BAYER_CTX1_FC_ABORT_DONE)
#define LWIS_PLATFORM_EVENT_ID_ISP_FE_CTX1_FC_LATE_CONFIG \
	EVENT_ID(ISP_FE_FC_BAYER_CTX1_BASE, \
		 ISP_FE_FC_BAYER_CTX1_FC_LATE_CONFIG)
#define LWIS_PLATFORM_EVENT_ID_ISP_FE_CTX1_FC_ERROR \
	EVENT_ID(ISP_FE_FC_BAYER_CTX1_BASE, \
		 ISP_FE_FC_BAYER_CTX1_FC_ERROR)
#define LWIS_PLATFORM_EVENT_ID_ISP_FE_CTX1_SPD_WDMA_BUS_ERROR \
	EVENT_ID(ISP_FE_FC_BAYER_CTX1_BASE, \
		 ISP_FE_FC_BAYER_CTX1_SPD_WDMA_BUS_ERROR)
#define LWIS_PLATFORM_EVENT_ID_ISP_FE_CTX1_LMP_IDMA0_BUS_ERROR \
	EVENT_ID(ISP_FE_FC_BAYER_CTX1_BASE, \
		 ISP_FE_FC_BAYER_CTX1_LMP_IDMA0_BUS_ERROR)
#define LWIS_PLATFORM_EVENT_ID_ISP_FE_CTX1_LMP_IDMA1_BUS_ERROR \
	EVENT_ID(ISP_FE_FC_BAYER_CTX1_BASE, \
		 ISP_FE_FC_BAYER_CTX1_LMP_IDMA1_BUS_ERROR)

#define LWIS_PLATFORM_EVENT_ID_ISP_FE_CTX2_FC_SOF \
	EVENT_ID(ISP_FE_FC_BAYER_CTX2_BASE, \
		 ISP_FE_FC_BAYER_CTX2_FC_SOF)
#define LWIS_PLATFORM_EVENT_ID_ISP_FE_CTX2_FC_EOF \
	EVENT_ID(ISP_FE_FC_BAYER_CTX2_BASE, \
		 ISP_FE_FC_BAYER_CTX2_FC_EOF)
#define LWIS_PLATFORM_EVENT_ID_ISP_FE_CTX2_FC_REG_UPDATED \
	EVENT_ID(ISP_FE_FC_BAYER_CTX2_BASE, \
		 ISP_FE_FC_BAYER_CTX2_FC_REG_UPDATED)
#define LWIS_PLATFORM_EVENT_ID_ISP_FE_CTX2_FC_ABORT_START \
	EVENT_ID(ISP_FE_FC_BAYER_CTX2_BASE, \
		 ISP_FE_FC_BAYER_CTX2_FC_ABORT_START)
#define LWIS_PLATFORM_EVENT_ID_ISP_FE_CTX2_FC_ABORT_DMA_CMPLT \
	EVENT_ID(ISP_FE_FC_BAYER_CTX2_BASE, \
		 ISP_FE_FC_BAYER_CTX2_FC_ABORT_DMA_CMPLT)
#define LWIS_PLATFORM_EVENT_ID_ISP_FE_CTX2_FC_ABORT_DONE \
	EVENT_ID(ISP_FE_FC_BAYER_CTX2_BASE, \
		 ISP_FE_FC_BAYER_CTX2_FC_ABORT_DONE)
#define LWIS_PLATFORM_EVENT_ID_ISP_FE_CTX2_FC_LATE_CONFIG \
	EVENT_ID(ISP_FE_FC_BAYER_CTX2_BASE, \
		 ISP_FE_FC_BAYER_CTX2_FC_LATE_CONFIG)
#define LWIS_PLATFORM_EVENT_ID_ISP_FE_CTX2_FC_ERROR \
	EVENT_ID(ISP_FE_FC_BAYER_CTX2_BASE, \
		 ISP_FE_FC_BAYER_CTX2_FC_ERROR)
#define LWIS_PLATFORM_EVENT_ID_ISP_FE_CTX2_SPD_WDMA_BUS_ERROR \
	EVENT_ID(ISP_FE_FC_BAYER_CTX2_BASE, \
		 ISP_FE_FC_BAYER_CTX2_SPD_WDMA_BUS_ERROR)
#define LWIS_PLATFORM_EVENT_ID_ISP_FE_CTX2_LMP_IDMA0_BUS_ERROR \
	EVENT_ID(ISP_FE_FC_BAYER_CTX2_BASE, \
		 ISP_FE_FC_BAYER_CTX2_LMP_IDMA0_BUS_ERROR)
#define LWIS_PLATFORM_EVENT_ID_ISP_FE_CTX2_LMP_IDMA1_BUS_ERROR \
	EVENT_ID(ISP_FE_FC_BAYER_CTX2_BASE, \
		 ISP_FE_FC_BAYER_CTX2_LMP_IDMA1_BUS_ERROR)

#define LWIS_PLATFORM_EVENT_ID_ISP_FE_CTX3_FC_SOF \
	EVENT_ID(ISP_FE_FC_BAYER_CTX3_BASE, \
		 ISP_FE_FC_BAYER_CTX3_FC_SOF)
#define LWIS_PLATFORM_EVENT_ID_ISP_FE_CTX3_FC_EOF \
	EVENT_ID(ISP_FE_FC_BAYER_CTX3_BASE, \
		 ISP_FE_FC_BAYER_CTX3_FC_EOF)
#define LWIS_PLATFORM_EVENT_ID_ISP_FE_CTX3_FC_REG_UPDATED \
	EVENT_ID(ISP_FE_FC_BAYER_CTX3_BASE, \
		 ISP_FE_FC_BAYER_CTX3_FC_REG_UPDATED)
#define LWIS_PLATFORM_EVENT_ID_ISP_FE_CTX3_FC_ABORT_START \
	EVENT_ID(ISP_FE_FC_BAYER_CTX3_BASE, \
		 ISP_FE_FC_BAYER_CTX3_FC_ABORT_START)
#define LWIS_PLATFORM_EVENT_ID_ISP_FE_CTX3_FC_ABORT_DMA_CMPLT \
	EVENT_ID(ISP_FE_FC_BAYER_CTX3_BASE, \
		 ISP_FE_FC_BAYER_CTX3_FC_ABORT_DMA_CMPLT)
#define LWIS_PLATFORM_EVENT_ID_ISP_FE_CTX3_FC_ABORT_DONE \
	EVENT_ID(ISP_FE_FC_BAYER_CTX3_BASE, \
		 ISP_FE_FC_BAYER_CTX3_FC_ABORT_DONE)
#define LWIS_PLATFORM_EVENT_ID_ISP_FE_CTX3_FC_LATE_CONFIG \
	EVENT_ID(ISP_FE_FC_BAYER_CTX3_BASE, \
		 ISP_FE_FC_BAYER_CTX3_FC_LATE_CONFIG)
#define LWIS_PLATFORM_EVENT_ID_ISP_FE_CTX3_FC_ERROR \
	EVENT_ID(ISP_FE_FC_BAYER_CTX3_BASE, \
		 ISP_FE_FC_BAYER_CTX3_FC_ERROR)
#define LWIS_PLATFORM_EVENT_ID_ISP_FE_CTX3_SPD_WDMA_BUS_ERROR \
	EVENT_ID(ISP_FE_FC_BAYER_CTX3_BASE, \
		 ISP_FE_FC_BAYER_CTX3_SPD_WDMA_BUS_ERROR)
#define LWIS_PLATFORM_EVENT_ID_ISP_FE_CTX3_LMP_IDMA0_BUS_ERROR \
	EVENT_ID(ISP_FE_FC_BAYER_CTX3_BASE, \
		 ISP_FE_FC_BAYER_CTX3_LMP_IDMA0_BUS_ERROR)
#define LWIS_PLATFORM_EVENT_ID_ISP_FE_CTX3_LMP_IDMA1_BUS_ERROR \
	EVENT_ID(ISP_FE_FC_BAYER_CTX3_BASE, \
		 ISP_FE_FC_BAYER_CTX3_LMP_IDMA1_BUS_ERROR)

#define LWIS_PLATFORM_EVENT_ID_ISP_FE_CTX4_FC_SOF \
	EVENT_ID(ISP_FE_FC_BAYER_CTX4_BASE, \
		 ISP_FE_FC_BAYER_CTX4_FC_SOF)
#define LWIS_PLATFORM_EVENT_ID_ISP_FE_CTX4_FC_EOF \
	EVENT_ID(ISP_FE_FC_BAYER_CTX4_BASE, \
		 ISP_FE_FC_BAYER_CTX4_FC_EOF)
#define LWIS_PLATFORM_EVENT_ID_ISP_FE_CTX4_FC_REG_UPDATED \
	EVENT_ID(ISP_FE_FC_BAYER_CTX4_BASE, \
		 ISP_FE_FC_BAYER_CTX4_FC_REG_UPDATED)
#define LWIS_PLATFORM_EVENT_ID_ISP_FE_CTX4_FC_ABORT_START \
	EVENT_ID(ISP_FE_FC_BAYER_CTX4_BASE, \
		 ISP_FE_FC_BAYER_CTX4_FC_ABORT_START)
#define LWIS_PLATFORM_EVENT_ID_ISP_FE_CTX4_FC_ABORT_DMA_CMPLT \
	EVENT_ID(ISP_FE_FC_BAYER_CTX4_BASE, \
		 ISP_FE_FC_BAYER_CTX4_FC_ABORT_DMA_CMPLT)
#define LWIS_PLATFORM_EVENT_ID_ISP_FE_CTX4_FC_ABORT_DONE \
	EVENT_ID(ISP_FE_FC_BAYER_CTX4_BASE, \
		 ISP_FE_FC_BAYER_CTX4_FC_ABORT_DONE)
#define LWIS_PLATFORM_EVENT_ID_ISP_FE_CTX4_FC_LATE_CONFIG \
	EVENT_ID(ISP_FE_FC_BAYER_CTX4_BASE, \
		 ISP_FE_FC_BAYER_CTX4_FC_LATE_CONFIG)
#define LWIS_PLATFORM_EVENT_ID_ISP_FE_CTX4_FC_ERROR \
	EVENT_ID(ISP_FE_FC_BAYER_CTX4_BASE, \
		 ISP_FE_FC_BAYER_CTX4_FC_ERROR)
#define LWIS_PLATFORM_EVENT_ID_ISP_FE_CTX4_SPD_WDMA_BUS_ERROR \
	EVENT_ID(ISP_FE_FC_BAYER_CTX4_BASE, \
		 ISP_FE_FC_BAYER_CTX4_SPD_WDMA_BUS_ERROR)
#define LWIS_PLATFORM_EVENT_ID_ISP_FE_CTX4_LMP_IDMA0_BUS_ERROR \
	EVENT_ID(ISP_FE_FC_BAYER_CTX4_BASE, \
		 ISP_FE_FC_BAYER_CTX4_LMP_IDMA0_BUS_ERROR)
#define LWIS_PLATFORM_EVENT_ID_ISP_FE_CTX4_LMP_IDMA1_BUS_ERROR \
	EVENT_ID(ISP_FE_FC_BAYER_CTX4_BASE, \
		 ISP_FE_FC_BAYER_CTX4_LMP_IDMA1_BUS_ERROR)

#define LWIS_PLATFORM_EVENT_ID_ISP_FE_CTX0_PDAF_LATE_CONFIG \
	EVENT_ID(ISP_FE_FC_PDAF_CTX0_BASE, \
		 ISP_FE_FC_PDAF_CTX0_PDAF_LATE_CONFIG)
#define LWIS_PLATFORM_EVENT_ID_ISP_FE_CTX0_PDAF_ERROR \
	EVENT_ID(ISP_FE_FC_PDAF_CTX0_BASE, \
		 ISP_FE_FC_PDAF_CTX0_PDAF_ERROR)

#define LWIS_PLATFORM_EVENT_ID_ISP_FE_CTX1_PDAF_LATE_CONFIG \
	EVENT_ID(ISP_FE_FC_PDAF_CTX1_BASE, \
		 ISP_FE_FC_PDAF_CTX1_PDAF_LATE_CONFIG)
#define LWIS_PLATFORM_EVENT_ID_ISP_FE_CTX1_PDAF_ERROR \
	EVENT_ID(ISP_FE_FC_PDAF_CTX1_BASE, \
		 ISP_FE_FC_PDAF_CTX1_PDAF_ERROR)

#define LWIS_PLATFORM_EVENT_ID_ISP_FE_CTX2_PDAF_LATE_CONFIG \
	EVENT_ID(ISP_FE_FC_PDAF_CTX2_BASE, \
		 ISP_FE_FC_PDAF_CTX2_PDAF_LATE_CONFIG)
#define LWIS_PLATFORM_EVENT_ID_ISP_FE_CTX2_PDAF_ERROR \
	EVENT_ID(ISP_FE_FC_PDAF_CTX2_BASE, \
		 ISP_FE_FC_PDAF_CTX2_PDAF_ERROR)

#define LWIS_PLATFORM_EVENT_ID_ISP_FE_CTX3_PDAF_LATE_CONFIG \
	EVENT_ID(ISP_FE_FC_PDAF_CTX3_BASE, \
		 ISP_FE_FC_PDAF_CTX3_PDAF_LATE_CONFIG)
#define LWIS_PLATFORM_EVENT_ID_ISP_FE_CTX3_PDAF_ERROR \
	EVENT_ID(ISP_FE_FC_PDAF_CTX3_BASE, \
		 ISP_FE_FC_PDAF_CTX3_PDAF_ERROR)

#define LWIS_PLATFORM_EVENT_ID_ISP_FE_CTX0_IRQ_CMD \
	EVENT_ID(ISP_FE_PDMA_CTX0_BASE, \
		 ISP_FE_PDMA_CTX0_IRQ_CMD)
#define LWIS_PLATFORM_EVENT_ID_ISP_FE_CTX0_ALMOST_EMPTY \
	EVENT_ID(ISP_FE_PDMA_CTX0_BASE, \
		 ISP_FE_PDMA_CTX0_ALMOST_EMPTY)

#define LWIS_PLATFORM_EVENT_ID_ISP_FE_CTX1_IRQ_CMD \
	EVENT_ID(ISP_FE_PDMA_CTX1_BASE, \
		 ISP_FE_PDMA_CTX1_IRQ_CMD)
#define LWIS_PLATFORM_EVENT_ID_ISP_FE_CTX1_ALMOST_EMPTY \
	EVENT_ID(ISP_FE_PDMA_CTX1_BASE, \
		 ISP_FE_PDMA_CTX1_ALMOST_EMPTY)

#define LWIS_PLATFORM_EVENT_ID_ISP_FE_CTX2_IRQ_CMD \
	EVENT_ID(ISP_FE_PDMA_CTX2_BASE, \
		 ISP_FE_PDMA_CTX2_IRQ_CMD)
#define LWIS_PLATFORM_EVENT_ID_ISP_FE_CTX2_ALMOST_EMPTY \
	EVENT_ID(ISP_FE_PDMA_CTX2_BASE, \
		 ISP_FE_PDMA_CTX2_ALMOST_EMPTY)

#define LWIS_PLATFORM_EVENT_ID_ISP_FE_CTX3_IRQ_CMD \
	EVENT_ID(ISP_FE_PDMA_CTX3_BASE, \
		 ISP_FE_PDMA_CTX3_IRQ_CMD)
#define LWIS_PLATFORM_EVENT_ID_ISP_FE_CTX3_ALMOST_EMPTY \
	EVENT_ID(ISP_FE_PDMA_CTX3_BASE, \
		 ISP_FE_PDMA_CTX3_ALMOST_EMPTY)

#define LWIS_PLATFORM_EVENT_ID_ISP_FE_CTX4_IRQ_CMD \
	EVENT_ID(ISP_FE_PDMA_CTX4_BASE, \
		 ISP_FE_PDMA_CTX4_IRQ_CMD)
#define LWIS_PLATFORM_EVENT_ID_ISP_FE_CTX4_ALMOST_EMPTY \
	EVENT_ID(ISP_FE_PDMA_CTX4_BASE, \
		 ISP_FE_PDMA_CTX4_ALMOST_EMPTY)

#define LWIS_PLATFORM_EVENT_ID_ISP_FE_CTX0_MEM_BUS_ERR \
	EVENT_ID(ISP_FE_PDMA_ERR_CTX0_BASE, \
		 ISP_FE_PDMA_ERR_CTX0_MEM_BUS_ERR)
#define LWIS_PLATFORM_EVENT_ID_ISP_FE_CTX0_CSR_BUS_ERR \
	EVENT_ID(ISP_FE_PDMA_ERR_CTX0_BASE, \
		 ISP_FE_PDMA_ERR_CTX0_CSR_BUS_ERR)
#define LWIS_PLATFORM_EVENT_ID_ISP_FE_CTX0_ILLEGAL_CMD \
	EVENT_ID(ISP_FE_PDMA_ERR_CTX0_BASE, \
		 ISP_FE_PDMA_ERR_CTX0_ILLEGAL_CMD)
#define LWIS_PLATFORM_EVENT_ID_ISP_FE_CTX0_RECUR_INDIR_CMD \
	EVENT_ID(ISP_FE_PDMA_ERR_CTX0_BASE, \
		 ISP_FE_PDMA_ERR_CTX0_RECUR_INDIR_CMD)
#define LWIS_PLATFORM_EVENT_ID_ISP_FE_CTX0_CMD_SIZE_MISMATCH \
	EVENT_ID(ISP_FE_PDMA_ERR_CTX0_BASE, \
		 ISP_FE_PDMA_ERR_CTX0_CMD_SIZE_MISMATCH)

#define LWIS_PLATFORM_EVENT_ID_ISP_FE_CTX1_MEM_BUS_ERR \
	EVENT_ID(ISP_FE_PDMA_ERR_CTX1_BASE, \
		 ISP_FE_PDMA_ERR_CTX1_MEM_BUS_ERR)
#define LWIS_PLATFORM_EVENT_ID_ISP_FE_CTX1_CSR_BUS_ERR \
	EVENT_ID(ISP_FE_PDMA_ERR_CTX1_BASE, \
		 ISP_FE_PDMA_ERR_CTX1_CSR_BUS_ERR)
#define LWIS_PLATFORM_EVENT_ID_ISP_FE_CTX1_ILLEGAL_CMD \
	EVENT_ID(ISP_FE_PDMA_ERR_CTX1_BASE, \
		 ISP_FE_PDMA_ERR_CTX1_ILLEGAL_CMD)
#define LWIS_PLATFORM_EVENT_ID_ISP_FE_CTX1_RECUR_INDIR_CMD \
	EVENT_ID(ISP_FE_PDMA_ERR_CTX1_BASE, \
		 ISP_FE_PDMA_ERR_CTX1_RECUR_INDIR_CMD)
#define LWIS_PLATFORM_EVENT_ID_ISP_FE_CTX1_CMD_SIZE_MISMATCH \
	EVENT_ID(ISP_FE_PDMA_ERR_CTX1_BASE, \
		 ISP_FE_PDMA_ERR_CTX1_CMD_SIZE_MISMATCH)

#define LWIS_PLATFORM_EVENT_ID_ISP_FE_CTX2_MEM_BUS_ERR \
	EVENT_ID(ISP_FE_PDMA_ERR_CTX2_BASE, \
		 ISP_FE_PDMA_ERR_CTX2_MEM_BUS_ERR)
#define LWIS_PLATFORM_EVENT_ID_ISP_FE_CTX2_CSR_BUS_ERR \
	EVENT_ID(ISP_FE_PDMA_ERR_CTX2_BASE, \
		 ISP_FE_PDMA_ERR_CTX2_CSR_BUS_ERR)
#define LWIS_PLATFORM_EVENT_ID_ISP_FE_CTX2_ILLEGAL_CMD \
	EVENT_ID(ISP_FE_PDMA_ERR_CTX2_BASE, \
		 ISP_FE_PDMA_ERR_CTX2_ILLEGAL_CMD)
#define LWIS_PLATFORM_EVENT_ID_ISP_FE_CTX2_RECUR_INDIR_CMD \
	EVENT_ID(ISP_FE_PDMA_ERR_CTX2_BASE, \
		 ISP_FE_PDMA_ERR_CTX2_RECUR_INDIR_CMD)
#define LWIS_PLATFORM_EVENT_ID_ISP_FE_CTX2_CMD_SIZE_MISMATCH \
	EVENT_ID(ISP_FE_PDMA_ERR_CTX2_BASE, \
		 ISP_FE_PDMA_ERR_CTX2_CMD_SIZE_MISMATCH)

#define LWIS_PLATFORM_EVENT_ID_ISP_FE_CTX3_MEM_BUS_ERR \
	EVENT_ID(ISP_FE_PDMA_ERR_CTX3_BASE, \
		 ISP_FE_PDMA_ERR_CTX3_MEM_BUS_ERR)
#define LWIS_PLATFORM_EVENT_ID_ISP_FE_CTX3_CSR_BUS_ERR \
	EVENT_ID(ISP_FE_PDMA_ERR_CTX3_BASE, \
		 ISP_FE_PDMA_ERR_CTX3_CSR_BUS_ERR)
#define LWIS_PLATFORM_EVENT_ID_ISP_FE_CTX3_ILLEGAL_CMD \
	EVENT_ID(ISP_FE_PDMA_ERR_CTX3_BASE, \
		 ISP_FE_PDMA_ERR_CTX3_ILLEGAL_CMD)
#define LWIS_PLATFORM_EVENT_ID_ISP_FE_CTX3_RECUR_INDIR_CMD \
	EVENT_ID(ISP_FE_PDMA_ERR_CTX3_BASE, \
		 ISP_FE_PDMA_ERR_CTX3_RECUR_INDIR_CMD)
#define LWIS_PLATFORM_EVENT_ID_ISP_FE_CTX3_CMD_SIZE_MISMATCH \
	EVENT_ID(ISP_FE_PDMA_ERR_CTX3_BASE, \
		 ISP_FE_PDMA_ERR_CTX3_CMD_SIZE_MISMATCH)

#define LWIS_PLATFORM_EVENT_ID_ISP_FE_CTX4_MEM_BUS_ERR \
	EVENT_ID(ISP_FE_PDMA_ERR_CTX4_BASE, \
		 ISP_FE_PDMA_ERR_CTX4_MEM_BUS_ERR)
#define LWIS_PLATFORM_EVENT_ID_ISP_FE_CTX4_CSR_BUS_ERR \
	EVENT_ID(ISP_FE_PDMA_ERR_CTX4_BASE, \
		 ISP_FE_PDMA_ERR_CTX4_CSR_BUS_ERR)
#define LWIS_PLATFORM_EVENT_ID_ISP_FE_CTX4_ILLEGAL_CMD \
	EVENT_ID(ISP_FE_PDMA_ERR_CTX4_BASE, \
		 ISP_FE_PDMA_ERR_CTX4_ILLEGAL_CMD)
#define LWIS_PLATFORM_EVENT_ID_ISP_FE_CTX4_RECUR_INDIR_CMD \
	EVENT_ID(ISP_FE_PDMA_ERR_CTX4_BASE, \
		 ISP_FE_PDMA_ERR_CTX4_RECUR_INDIR_CMD)
#define LWIS_PLATFORM_EVENT_ID_ISP_FE_CTX4_CMD_SIZE_MISMATCH \
	EVENT_ID(ISP_FE_PDMA_ERR_CTX4_BASE, \
		 ISP_FE_PDMA_ERR_CTX4_CMD_SIZE_MISMATCH)

#define LWIS_PLATFORM_EVENT_ID_ISP_FE_CTX0_SW_RESET_DONE \
	EVENT_ID(ISP_FE_PDMA_RSTCTL_CTX0_BASE, \
		 ISP_FE_PDMA_RSTCTL_CTX0_SW_RESET_DONE)
#define LWIS_PLATFORM_EVENT_ID_ISP_FE_CTX0_INPUT_FLUSH_DONE \
	EVENT_ID(ISP_FE_PDMA_RSTCTL_CTX0_BASE, \
		 ISP_FE_PDMA_RSTCTL_CTX0_INPUT_FLUSH_DONE)
#define LWIS_PLATFORM_EVENT_ID_ISP_FE_CTX0_SW_MODE \
	EVENT_ID(ISP_FE_PDMA_RSTCTL_CTX0_BASE, \
		 ISP_FE_PDMA_RSTCTL_CTX0_SW_MODE)
#define LWIS_PLATFORM_EVENT_ID_ISP_FE_CTX0_APB_GKP_ERR \
	EVENT_ID(ISP_FE_PDMA_RSTCTL_CTX0_BASE, \
		 ISP_FE_PDMA_RSTCTL_CTX0_APB_GKP_ERR)
#define LWIS_PLATFORM_EVENT_ID_ISP_FE_CTX0_AXI_GKP_ERR \
	EVENT_ID(ISP_FE_PDMA_RSTCTL_CTX0_BASE, \
		 ISP_FE_PDMA_RSTCTL_CTX0_AXI_GKP_ERR)

#define LWIS_PLATFORM_EVENT_ID_ISP_FE_CTX1_SW_RESET_DONE \
	EVENT_ID(ISP_FE_PDMA_RSTCTL_CTX1_BASE, \
		 ISP_FE_PDMA_RSTCTL_CTX1_SW_RESET_DONE)
#define LWIS_PLATFORM_EVENT_ID_ISP_FE_CTX1_INPUT_FLUSH_DONE \
	EVENT_ID(ISP_FE_PDMA_RSTCTL_CTX1_BASE, \
		 ISP_FE_PDMA_RSTCTL_CTX1_INPUT_FLUSH_DONE)
#define LWIS_PLATFORM_EVENT_ID_ISP_FE_CTX1_SW_MODE \
	EVENT_ID(ISP_FE_PDMA_RSTCTL_CTX1_BASE, \
		 ISP_FE_PDMA_RSTCTL_CTX1_SW_MODE)
#define LWIS_PLATFORM_EVENT_ID_ISP_FE_CTX1_APB_GKP_ERR \
	EVENT_ID(ISP_FE_PDMA_RSTCTL_CTX1_BASE, \
		 ISP_FE_PDMA_RSTCTL_CTX1_APB_GKP_ERR)
#define LWIS_PLATFORM_EVENT_ID_ISP_FE_CTX1_AXI_GKP_ERR \
	EVENT_ID(ISP_FE_PDMA_RSTCTL_CTX1_BASE, \
		 ISP_FE_PDMA_RSTCTL_CTX1_AXI_GKP_ERR)

#define LWIS_PLATFORM_EVENT_ID_ISP_FE_CTX2_SW_RESET_DONE \
	EVENT_ID(ISP_FE_PDMA_RSTCTL_CTX2_BASE, \
		 ISP_FE_PDMA_RSTCTL_CTX2_SW_RESET_DONE)
#define LWIS_PLATFORM_EVENT_ID_ISP_FE_CTX2_INPUT_FLUSH_DONE \
	EVENT_ID(ISP_FE_PDMA_RSTCTL_CTX2_BASE, \
		 ISP_FE_PDMA_RSTCTL_CTX2_INPUT_FLUSH_DONE)
#define LWIS_PLATFORM_EVENT_ID_ISP_FE_CTX2_SW_MODE \
	EVENT_ID(ISP_FE_PDMA_RSTCTL_CTX2_BASE, \
		 ISP_FE_PDMA_RSTCTL_CTX2_SW_MODE)
#define LWIS_PLATFORM_EVENT_ID_ISP_FE_CTX2_APB_GKP_ERR \
	EVENT_ID(ISP_FE_PDMA_RSTCTL_CTX2_BASE, \
		 ISP_FE_PDMA_RSTCTL_CTX2_APB_GKP_ERR)
#define LWIS_PLATFORM_EVENT_ID_ISP_FE_CTX2_AXI_GKP_ERR \
	EVENT_ID(ISP_FE_PDMA_RSTCTL_CTX2_BASE, \
		 ISP_FE_PDMA_RSTCTL_CTX2_AXI_GKP_ERR)

#define LWIS_PLATFORM_EVENT_ID_ISP_FE_CTX3_SW_RESET_DONE \
	EVENT_ID(ISP_FE_PDMA_RSTCTL_CTX3_BASE, \
		 ISP_FE_PDMA_RSTCTL_CTX3_SW_RESET_DONE)
#define LWIS_PLATFORM_EVENT_ID_ISP_FE_CTX3_INPUT_FLUSH_DONE \
	EVENT_ID(ISP_FE_PDMA_RSTCTL_CTX3_BASE, \
		 ISP_FE_PDMA_RSTCTL_CTX3_INPUT_FLUSH_DONE)
#define LWIS_PLATFORM_EVENT_ID_ISP_FE_CTX3_SW_MODE \
	EVENT_ID(ISP_FE_PDMA_RSTCTL_CTX3_BASE, \
		 ISP_FE_PDMA_RSTCTL_CTX3_SW_MODE)
#define LWIS_PLATFORM_EVENT_ID_ISP_FE_CTX3_APB_GKP_ERR \
	EVENT_ID(ISP_FE_PDMA_RSTCTL_CTX3_BASE, \
		 ISP_FE_PDMA_RSTCTL_CTX3_APB_GKP_ERR)
#define LWIS_PLATFORM_EVENT_ID_ISP_FE_CTX3_AXI_GKP_ERR \
	EVENT_ID(ISP_FE_PDMA_RSTCTL_CTX3_BASE, \
		 ISP_FE_PDMA_RSTCTL_CTX3_AXI_GKP_ERR)

#define LWIS_PLATFORM_EVENT_ID_ISP_FE_CTX4_SW_RESET_DONE \
	EVENT_ID(ISP_FE_PDMA_RSTCTL_CTX4_BASE, \
		 ISP_FE_PDMA_RSTCTL_CTX4_SW_RESET_DONE)
#define LWIS_PLATFORM_EVENT_ID_ISP_FE_CTX4_INPUT_FLUSH_DONE \
	EVENT_ID(ISP_FE_PDMA_RSTCTL_CTX4_BASE, \
		 ISP_FE_PDMA_RSTCTL_CTX4_INPUT_FLUSH_DONE)
#define LWIS_PLATFORM_EVENT_ID_ISP_FE_CTX4_SW_MODE \
	EVENT_ID(ISP_FE_PDMA_RSTCTL_CTX4_BASE, \
		 ISP_FE_PDMA_RSTCTL_CTX4_SW_MODE)
#define LWIS_PLATFORM_EVENT_ID_ISP_FE_CTX4_APB_GKP_ERR \
	EVENT_ID(ISP_FE_PDMA_RSTCTL_CTX4_BASE, \
		 ISP_FE_PDMA_RSTCTL_CTX4_APB_GKP_ERR)
#define LWIS_PLATFORM_EVENT_ID_ISP_FE_CTX4_AXI_GKP_ERR \
	EVENT_ID(ISP_FE_PDMA_RSTCTL_CTX4_BASE, \
		 ISP_FE_PDMA_RSTCTL_CTX4_AXI_GKP_ERR)

#define LWIS_PLATFORM_EVENT_ID_ISP_FE_CTX0_REGISTER_UPDATE \
	EVENT_ID(ISP_FE_LMP_BAYER_CTX0_BASE, \
		 ISP_FE_LMP_BAYER_CTX0_REGISTER_UPDATE)
#define LWIS_PLATFORM_EVENT_ID_ISP_FE_CTX0_EOF \
	EVENT_ID(ISP_FE_LMP_BAYER_CTX0_BASE, \
		 ISP_FE_LMP_BAYER_CTX0_EOF)
#define LWIS_PLATFORM_EVENT_ID_ISP_FE_CTX0_END_OF_BATCH \
	EVENT_ID(ISP_FE_LMP_BAYER_CTX0_BASE, \
		 ISP_FE_LMP_BAYER_CTX0_END_OF_BATCH)
#define LWIS_PLATFORM_EVENT_ID_ISP_FE_CTX0_FE_LMP_ERROR \
	EVENT_ID(ISP_FE_LMP_BAYER_CTX0_BASE, \
		 ISP_FE_LMP_BAYER_CTX0_FE_LMP_ERROR)
#define LWIS_PLATFORM_EVENT_ID_ISP_FE_CTX0_CDAF_PRIMARY \
	EVENT_ID(ISP_FE_LMP_BAYER_CTX0_BASE, \
		 ISP_FE_LMP_BAYER_CTX0_CDAF_PRIMARY)
#define LWIS_PLATFORM_EVENT_ID_ISP_FE_CTX0_CDAF_WINDOWS \
	EVENT_ID(ISP_FE_LMP_BAYER_CTX0_BASE, \
		 ISP_FE_LMP_BAYER_CTX0_CDAF_WINDOWS)
#define LWIS_PLATFORM_EVENT_ID_ISP_FE_CTX0_PRE_LSC_AE_STATS \
	EVENT_ID(ISP_FE_LMP_BAYER_CTX0_BASE, \
		 ISP_FE_LMP_BAYER_CTX0_PRE_LSC_AE_STATS)
#define LWIS_PLATFORM_EVENT_ID_ISP_FE_CTX0_AWB_STATS \
	EVENT_ID(ISP_FE_LMP_BAYER_CTX0_BASE, \
		 ISP_FE_LMP_BAYER_CTX0_AWB_STATS)
#define LWIS_PLATFORM_EVENT_ID_ISP_FE_CTX0_LSC_STATS \
	EVENT_ID(ISP_FE_LMP_BAYER_CTX0_BASE, \
		 ISP_FE_LMP_BAYER_CTX0_LSC_STATS)
#define LWIS_PLATFORM_EVENT_ID_ISP_FE_CTX0_FLICKER_STATS \
	EVENT_ID(ISP_FE_LMP_BAYER_CTX0_BASE, \
		 ISP_FE_LMP_BAYER_CTX0_FLICKER_STATS)
#define LWIS_PLATFORM_EVENT_ID_ISP_FE_CTX0_HISTOGRAM0 \
	EVENT_ID(ISP_FE_LMP_BAYER_CTX0_BASE, \
		 ISP_FE_LMP_BAYER_CTX0_HISTOGRAM0)
#define LWIS_PLATFORM_EVENT_ID_ISP_FE_CTX0_HISTOGRAM1 \
	EVENT_ID(ISP_FE_LMP_BAYER_CTX0_BASE, \
		 ISP_FE_LMP_BAYER_CTX0_HISTOGRAM1)
#define LWIS_PLATFORM_EVENT_ID_ISP_FE_CTX0_HISTOGRAM2 \
	EVENT_ID(ISP_FE_LMP_BAYER_CTX0_BASE, \
		 ISP_FE_LMP_BAYER_CTX0_HISTOGRAM2)
#define LWIS_PLATFORM_EVENT_ID_ISP_FE_CTX0_POST_LSC_AE_STATS \
	EVENT_ID(ISP_FE_LMP_BAYER_CTX0_BASE, \
		 ISP_FE_LMP_BAYER_CTX0_POST_LSC_AE_STATS)
#define LWIS_PLATFORM_EVENT_ID_ISP_FE_CTX0_MOTION_METERING \
	EVENT_ID(ISP_FE_LMP_BAYER_CTX0_BASE, \
		 ISP_FE_LMP_BAYER_CTX0_MOTION_METERING)
#define LWIS_PLATFORM_EVENT_ID_ISP_FE_CTX0_BAYER0_WDMA \
	EVENT_ID(ISP_FE_LMP_BAYER_CTX0_BASE, \
		 ISP_FE_LMP_BAYER_CTX0_BAYER0_WDMA)
#define LWIS_PLATFORM_EVENT_ID_ISP_FE_CTX0_BAYER1_WDMA \
	EVENT_ID(ISP_FE_LMP_BAYER_CTX0_BASE, \
		 ISP_FE_LMP_BAYER_CTX0_BAYER1_WDMA)
#define LWIS_PLATFORM_EVENT_ID_ISP_FE_CTX0_LINEAR_RGB_OUTPUT \
	EVENT_ID(ISP_FE_LMP_BAYER_CTX0_BASE, \
		 ISP_FE_LMP_BAYER_CTX0_LINEAR_RGB_OUTPUT)
#define LWIS_PLATFORM_EVENT_ID_ISP_FE_CTX0_ML_OUTPUT0 \
	EVENT_ID(ISP_FE_LMP_BAYER_CTX0_BASE, \
		 ISP_FE_LMP_BAYER_CTX0_ML_OUTPUT0)
#define LWIS_PLATFORM_EVENT_ID_ISP_FE_CTX0_ML_OUTPUT1 \
	EVENT_ID(ISP_FE_LMP_BAYER_CTX0_BASE, \
		 ISP_FE_LMP_BAYER_CTX0_ML_OUTPUT1)
#define LWIS_PLATFORM_EVENT_ID_ISP_FE_CTX0_ML_OUTPUT2 \
	EVENT_ID(ISP_FE_LMP_BAYER_CTX0_BASE, \
		 ISP_FE_LMP_BAYER_CTX0_ML_OUTPUT2)
#define LWIS_PLATFORM_EVENT_ID_ISP_FE_CTX0_TNR_PYRAMID \
	EVENT_ID(ISP_FE_LMP_BAYER_CTX0_BASE, \
		 ISP_FE_LMP_BAYER_CTX0_TNR_PYRAMID)
#define LWIS_PLATFORM_EVENT_ID_ISP_FE_CTX0_MERGE1 \
	EVENT_ID(ISP_FE_LMP_BAYER_CTX0_BASE, \
		 ISP_FE_LMP_BAYER_CTX0_MERGE1)
#define LWIS_PLATFORM_EVENT_ID_ISP_FE_CTX0_MERGE2 \
	EVENT_ID(ISP_FE_LMP_BAYER_CTX0_BASE, \
		 ISP_FE_LMP_BAYER_CTX0_MERGE2)
#define LWIS_PLATFORM_EVENT_ID_ISP_FE_CTX0_MERGE3 \
	EVENT_ID(ISP_FE_LMP_BAYER_CTX0_BASE, \
		 ISP_FE_LMP_BAYER_CTX0_MERGE3)
#define LWIS_PLATFORM_EVENT_ID_ISP_FE_CTX0_MERGE4 \
	EVENT_ID(ISP_FE_LMP_BAYER_CTX0_BASE, \
		 ISP_FE_LMP_BAYER_CTX0_MERGE4)
#define LWIS_PLATFORM_EVENT_ID_ISP_FE_CTX0_MERGE5 \
	EVENT_ID(ISP_FE_LMP_BAYER_CTX0_BASE, \
		 ISP_FE_LMP_BAYER_CTX0_MERGE5)
#define LWIS_PLATFORM_EVENT_ID_ISP_FE_CTX0_MERGE6 \
	EVENT_ID(ISP_FE_LMP_BAYER_CTX0_BASE, \
		 ISP_FE_LMP_BAYER_CTX0_MERGE6)
#define LWIS_PLATFORM_EVENT_ID_ISP_FE_CTX0_LMP_BUS_ERROR \
	EVENT_ID(ISP_FE_LMP_BAYER_CTX0_BASE, \
		 ISP_FE_LMP_BAYER_CTX0_LMP_BUS_ERROR)
#define LWIS_PLATFORM_EVENT_ID_ISP_FE_CTX0_SOF \
	EVENT_ID(ISP_FE_LMP_BAYER_CTX0_BASE, \
		 ISP_FE_LMP_BAYER_CTX0_SOF)

#define LWIS_PLATFORM_EVENT_ID_ISP_FE_CTX1_REGISTER_UPDATE \
	EVENT_ID(ISP_FE_LMP_BAYER_CTX1_BASE, \
		 ISP_FE_LMP_BAYER_CTX1_REGISTER_UPDATE)
#define LWIS_PLATFORM_EVENT_ID_ISP_FE_CTX1_EOF \
	EVENT_ID(ISP_FE_LMP_BAYER_CTX1_BASE, \
		 ISP_FE_LMP_BAYER_CTX1_EOF)
#define LWIS_PLATFORM_EVENT_ID_ISP_FE_CTX1_END_OF_BATCH \
	EVENT_ID(ISP_FE_LMP_BAYER_CTX1_BASE, \
		 ISP_FE_LMP_BAYER_CTX1_END_OF_BATCH)
#define LWIS_PLATFORM_EVENT_ID_ISP_FE_CTX1_FE_LMP_ERROR \
	EVENT_ID(ISP_FE_LMP_BAYER_CTX1_BASE, \
		 ISP_FE_LMP_BAYER_CTX1_FE_LMP_ERROR)
#define LWIS_PLATFORM_EVENT_ID_ISP_FE_CTX1_CDAF_PRIMARY \
	EVENT_ID(ISP_FE_LMP_BAYER_CTX1_BASE, \
		 ISP_FE_LMP_BAYER_CTX1_CDAF_PRIMARY)
#define LWIS_PLATFORM_EVENT_ID_ISP_FE_CTX1_CDAF_WINDOWS \
	EVENT_ID(ISP_FE_LMP_BAYER_CTX1_BASE, \
		 ISP_FE_LMP_BAYER_CTX1_CDAF_WINDOWS)
#define LWIS_PLATFORM_EVENT_ID_ISP_FE_CTX1_PRE_LSC_AE_STATS \
	EVENT_ID(ISP_FE_LMP_BAYER_CTX1_BASE, \
		 ISP_FE_LMP_BAYER_CTX1_PRE_LSC_AE_STATS)
#define LWIS_PLATFORM_EVENT_ID_ISP_FE_CTX1_AWB_STATS \
	EVENT_ID(ISP_FE_LMP_BAYER_CTX1_BASE, \
		 ISP_FE_LMP_BAYER_CTX1_AWB_STATS)
#define LWIS_PLATFORM_EVENT_ID_ISP_FE_CTX1_LSC_STATS \
	EVENT_ID(ISP_FE_LMP_BAYER_CTX1_BASE, \
		 ISP_FE_LMP_BAYER_CTX1_LSC_STATS)
#define LWIS_PLATFORM_EVENT_ID_ISP_FE_CTX1_FLICKER_STATS \
	EVENT_ID(ISP_FE_LMP_BAYER_CTX1_BASE, \
		 ISP_FE_LMP_BAYER_CTX1_FLICKER_STATS)
#define LWIS_PLATFORM_EVENT_ID_ISP_FE_CTX1_HISTOGRAM0 \
	EVENT_ID(ISP_FE_LMP_BAYER_CTX1_BASE, \
		 ISP_FE_LMP_BAYER_CTX1_HISTOGRAM0)
#define LWIS_PLATFORM_EVENT_ID_ISP_FE_CTX1_HISTOGRAM1 \
	EVENT_ID(ISP_FE_LMP_BAYER_CTX1_BASE, \
		 ISP_FE_LMP_BAYER_CTX1_HISTOGRAM1)
#define LWIS_PLATFORM_EVENT_ID_ISP_FE_CTX1_HISTOGRAM2 \
	EVENT_ID(ISP_FE_LMP_BAYER_CTX1_BASE, \
		 ISP_FE_LMP_BAYER_CTX1_HISTOGRAM2)
#define LWIS_PLATFORM_EVENT_ID_ISP_FE_CTX1_POST_LSC_AE_STATS \
	EVENT_ID(ISP_FE_LMP_BAYER_CTX1_BASE, \
		 ISP_FE_LMP_BAYER_CTX1_POST_LSC_AE_STATS)
#define LWIS_PLATFORM_EVENT_ID_ISP_FE_CTX1_MOTION_METERING \
	EVENT_ID(ISP_FE_LMP_BAYER_CTX1_BASE, \
		 ISP_FE_LMP_BAYER_CTX1_MOTION_METERING)
#define LWIS_PLATFORM_EVENT_ID_ISP_FE_CTX1_BAYER0_WDMA \
	EVENT_ID(ISP_FE_LMP_BAYER_CTX1_BASE, \
		 ISP_FE_LMP_BAYER_CTX1_BAYER0_WDMA)
#define LWIS_PLATFORM_EVENT_ID_ISP_FE_CTX1_BAYER1_WDMA \
	EVENT_ID(ISP_FE_LMP_BAYER_CTX1_BASE, \
		 ISP_FE_LMP_BAYER_CTX1_BAYER1_WDMA)
#define LWIS_PLATFORM_EVENT_ID_ISP_FE_CTX1_LINEAR_RGB_OUTPUT \
	EVENT_ID(ISP_FE_LMP_BAYER_CTX1_BASE, \
		 ISP_FE_LMP_BAYER_CTX1_LINEAR_RGB_OUTPUT)
#define LWIS_PLATFORM_EVENT_ID_ISP_FE_CTX1_ML_OUTPUT0 \
	EVENT_ID(ISP_FE_LMP_BAYER_CTX1_BASE, \
		 ISP_FE_LMP_BAYER_CTX1_ML_OUTPUT0)
#define LWIS_PLATFORM_EVENT_ID_ISP_FE_CTX1_ML_OUTPUT1 \
	EVENT_ID(ISP_FE_LMP_BAYER_CTX1_BASE, \
		 ISP_FE_LMP_BAYER_CTX1_ML_OUTPUT1)
#define LWIS_PLATFORM_EVENT_ID_ISP_FE_CTX1_ML_OUTPUT2 \
	EVENT_ID(ISP_FE_LMP_BAYER_CTX1_BASE, \
		 ISP_FE_LMP_BAYER_CTX1_ML_OUTPUT2)
#define LWIS_PLATFORM_EVENT_ID_ISP_FE_CTX1_TNR_PYRAMID \
	EVENT_ID(ISP_FE_LMP_BAYER_CTX1_BASE, \
		 ISP_FE_LMP_BAYER_CTX1_TNR_PYRAMID)
#define LWIS_PLATFORM_EVENT_ID_ISP_FE_CTX1_MERGE1 \
	EVENT_ID(ISP_FE_LMP_BAYER_CTX1_BASE, \
		 ISP_FE_LMP_BAYER_CTX1_MERGE1)
#define LWIS_PLATFORM_EVENT_ID_ISP_FE_CTX1_MERGE2 \
	EVENT_ID(ISP_FE_LMP_BAYER_CTX1_BASE, \
		 ISP_FE_LMP_BAYER_CTX1_MERGE2)
#define LWIS_PLATFORM_EVENT_ID_ISP_FE_CTX1_MERGE3 \
	EVENT_ID(ISP_FE_LMP_BAYER_CTX1_BASE, \
		 ISP_FE_LMP_BAYER_CTX1_MERGE3)
#define LWIS_PLATFORM_EVENT_ID_ISP_FE_CTX1_MERGE4 \
	EVENT_ID(ISP_FE_LMP_BAYER_CTX1_BASE, \
		 ISP_FE_LMP_BAYER_CTX1_MERGE4)
#define LWIS_PLATFORM_EVENT_ID_ISP_FE_CTX1_MERGE5 \
	EVENT_ID(ISP_FE_LMP_BAYER_CTX1_BASE, \
		 ISP_FE_LMP_BAYER_CTX1_MERGE5)
#define LWIS_PLATFORM_EVENT_ID_ISP_FE_CTX1_MERGE6 \
	EVENT_ID(ISP_FE_LMP_BAYER_CTX1_BASE, \
		 ISP_FE_LMP_BAYER_CTX1_MERGE6)
#define LWIS_PLATFORM_EVENT_ID_ISP_FE_CTX1_LMP_BUS_ERROR \
	EVENT_ID(ISP_FE_LMP_BAYER_CTX1_BASE, \
		 ISP_FE_LMP_BAYER_CTX1_LMP_BUS_ERROR)
#define LWIS_PLATFORM_EVENT_ID_ISP_FE_CTX1_SOF \
	EVENT_ID(ISP_FE_LMP_BAYER_CTX1_BASE, \
		 ISP_FE_LMP_BAYER_CTX1_SOF)

#define LWIS_PLATFORM_EVENT_ID_ISP_FE_CTX2_REGISTER_UPDATE \
	EVENT_ID(ISP_FE_LMP_BAYER_CTX2_BASE, \
		 ISP_FE_LMP_BAYER_CTX2_REGISTER_UPDATE)
#define LWIS_PLATFORM_EVENT_ID_ISP_FE_CTX2_EOF \
	EVENT_ID(ISP_FE_LMP_BAYER_CTX2_BASE, \
		 ISP_FE_LMP_BAYER_CTX2_EOF)
#define LWIS_PLATFORM_EVENT_ID_ISP_FE_CTX2_END_OF_BATCH \
	EVENT_ID(ISP_FE_LMP_BAYER_CTX2_BASE, \
		 ISP_FE_LMP_BAYER_CTX2_END_OF_BATCH)
#define LWIS_PLATFORM_EVENT_ID_ISP_FE_CTX2_FE_LMP_ERROR \
	EVENT_ID(ISP_FE_LMP_BAYER_CTX2_BASE, \
		 ISP_FE_LMP_BAYER_CTX2_FE_LMP_ERROR)
#define LWIS_PLATFORM_EVENT_ID_ISP_FE_CTX2_CDAF_PRIMARY \
	EVENT_ID(ISP_FE_LMP_BAYER_CTX2_BASE, \
		 ISP_FE_LMP_BAYER_CTX2_CDAF_PRIMARY)
#define LWIS_PLATFORM_EVENT_ID_ISP_FE_CTX2_CDAF_WINDOWS \
	EVENT_ID(ISP_FE_LMP_BAYER_CTX2_BASE, \
		 ISP_FE_LMP_BAYER_CTX2_CDAF_WINDOWS)
#define LWIS_PLATFORM_EVENT_ID_ISP_FE_CTX2_PRE_LSC_AE_STATS \
	EVENT_ID(ISP_FE_LMP_BAYER_CTX2_BASE, \
		 ISP_FE_LMP_BAYER_CTX2_PRE_LSC_AE_STATS)
#define LWIS_PLATFORM_EVENT_ID_ISP_FE_CTX2_AWB_STATS \
	EVENT_ID(ISP_FE_LMP_BAYER_CTX2_BASE, \
		 ISP_FE_LMP_BAYER_CTX2_AWB_STATS)
#define LWIS_PLATFORM_EVENT_ID_ISP_FE_CTX2_LSC_STATS \
	EVENT_ID(ISP_FE_LMP_BAYER_CTX2_BASE, \
		 ISP_FE_LMP_BAYER_CTX2_LSC_STATS)
#define LWIS_PLATFORM_EVENT_ID_ISP_FE_CTX2_FLICKER_STATS \
	EVENT_ID(ISP_FE_LMP_BAYER_CTX2_BASE, \
		 ISP_FE_LMP_BAYER_CTX2_FLICKER_STATS)
#define LWIS_PLATFORM_EVENT_ID_ISP_FE_CTX2_HISTOGRAM0 \
	EVENT_ID(ISP_FE_LMP_BAYER_CTX2_BASE, \
		 ISP_FE_LMP_BAYER_CTX2_HISTOGRAM0)
#define LWIS_PLATFORM_EVENT_ID_ISP_FE_CTX2_HISTOGRAM1 \
	EVENT_ID(ISP_FE_LMP_BAYER_CTX2_BASE, \
		 ISP_FE_LMP_BAYER_CTX2_HISTOGRAM1)
#define LWIS_PLATFORM_EVENT_ID_ISP_FE_CTX2_HISTOGRAM2 \
	EVENT_ID(ISP_FE_LMP_BAYER_CTX2_BASE, \
		 ISP_FE_LMP_BAYER_CTX2_HISTOGRAM2)
#define LWIS_PLATFORM_EVENT_ID_ISP_FE_CTX2_POST_LSC_AE_STATS \
	EVENT_ID(ISP_FE_LMP_BAYER_CTX2_BASE, \
		 ISP_FE_LMP_BAYER_CTX2_POST_LSC_AE_STATS)
#define LWIS_PLATFORM_EVENT_ID_ISP_FE_CTX2_MOTION_METERING \
	EVENT_ID(ISP_FE_LMP_BAYER_CTX2_BASE, \
		 ISP_FE_LMP_BAYER_CTX2_MOTION_METERING)
#define LWIS_PLATFORM_EVENT_ID_ISP_FE_CTX2_BAYER0_WDMA \
	EVENT_ID(ISP_FE_LMP_BAYER_CTX2_BASE, \
		 ISP_FE_LMP_BAYER_CTX2_BAYER0_WDMA)
#define LWIS_PLATFORM_EVENT_ID_ISP_FE_CTX2_BAYER1_WDMA \
	EVENT_ID(ISP_FE_LMP_BAYER_CTX2_BASE, \
		 ISP_FE_LMP_BAYER_CTX2_BAYER1_WDMA)
#define LWIS_PLATFORM_EVENT_ID_ISP_FE_CTX2_LINEAR_RGB_OUTPUT \
	EVENT_ID(ISP_FE_LMP_BAYER_CTX2_BASE, \
		 ISP_FE_LMP_BAYER_CTX2_LINEAR_RGB_OUTPUT)
#define LWIS_PLATFORM_EVENT_ID_ISP_FE_CTX2_ML_OUTPUT0 \
	EVENT_ID(ISP_FE_LMP_BAYER_CTX2_BASE, \
		 ISP_FE_LMP_BAYER_CTX2_ML_OUTPUT0)
#define LWIS_PLATFORM_EVENT_ID_ISP_FE_CTX2_ML_OUTPUT1 \
	EVENT_ID(ISP_FE_LMP_BAYER_CTX2_BASE, \
		 ISP_FE_LMP_BAYER_CTX2_ML_OUTPUT1)
#define LWIS_PLATFORM_EVENT_ID_ISP_FE_CTX2_ML_OUTPUT2 \
	EVENT_ID(ISP_FE_LMP_BAYER_CTX2_BASE, \
		 ISP_FE_LMP_BAYER_CTX2_ML_OUTPUT2)
#define LWIS_PLATFORM_EVENT_ID_ISP_FE_CTX2_TNR_PYRAMID \
	EVENT_ID(ISP_FE_LMP_BAYER_CTX2_BASE, \
		 ISP_FE_LMP_BAYER_CTX2_TNR_PYRAMID)
#define LWIS_PLATFORM_EVENT_ID_ISP_FE_CTX2_MERGE1 \
	EVENT_ID(ISP_FE_LMP_BAYER_CTX2_BASE, \
		 ISP_FE_LMP_BAYER_CTX2_MERGE1)
#define LWIS_PLATFORM_EVENT_ID_ISP_FE_CTX2_MERGE2 \
	EVENT_ID(ISP_FE_LMP_BAYER_CTX2_BASE, \
		 ISP_FE_LMP_BAYER_CTX2_MERGE2)
#define LWIS_PLATFORM_EVENT_ID_ISP_FE_CTX2_MERGE3 \
	EVENT_ID(ISP_FE_LMP_BAYER_CTX2_BASE, \
		 ISP_FE_LMP_BAYER_CTX2_MERGE3)
#define LWIS_PLATFORM_EVENT_ID_ISP_FE_CTX2_MERGE4 \
	EVENT_ID(ISP_FE_LMP_BAYER_CTX2_BASE, \
		 ISP_FE_LMP_BAYER_CTX2_MERGE4)
#define LWIS_PLATFORM_EVENT_ID_ISP_FE_CTX2_MERGE5 \
	EVENT_ID(ISP_FE_LMP_BAYER_CTX2_BASE, \
		 ISP_FE_LMP_BAYER_CTX2_MERGE5)
#define LWIS_PLATFORM_EVENT_ID_ISP_FE_CTX2_MERGE6 \
	EVENT_ID(ISP_FE_LMP_BAYER_CTX2_BASE, \
		 ISP_FE_LMP_BAYER_CTX2_MERGE6)
#define LWIS_PLATFORM_EVENT_ID_ISP_FE_CTX2_LMP_BUS_ERROR \
	EVENT_ID(ISP_FE_LMP_BAYER_CTX2_BASE, \
		 ISP_FE_LMP_BAYER_CTX2_LMP_BUS_ERROR)
#define LWIS_PLATFORM_EVENT_ID_ISP_FE_CTX2_SOF \
	EVENT_ID(ISP_FE_LMP_BAYER_CTX2_BASE, \
		 ISP_FE_LMP_BAYER_CTX2_SOF)

#define LWIS_PLATFORM_EVENT_ID_ISP_FE_CTX3_REGISTER_UPDATE \
	EVENT_ID(ISP_FE_LMP_BAYER_CTX3_BASE, \
		 ISP_FE_LMP_BAYER_CTX3_REGISTER_UPDATE)
#define LWIS_PLATFORM_EVENT_ID_ISP_FE_CTX3_EOF \
	EVENT_ID(ISP_FE_LMP_BAYER_CTX3_BASE, \
		 ISP_FE_LMP_BAYER_CTX3_EOF)
#define LWIS_PLATFORM_EVENT_ID_ISP_FE_CTX3_END_OF_BATCH \
	EVENT_ID(ISP_FE_LMP_BAYER_CTX3_BASE, \
		 ISP_FE_LMP_BAYER_CTX3_END_OF_BATCH)
#define LWIS_PLATFORM_EVENT_ID_ISP_FE_CTX3_FE_LMP_ERROR \
	EVENT_ID(ISP_FE_LMP_BAYER_CTX3_BASE, \
		 ISP_FE_LMP_BAYER_CTX3_FE_LMP_ERROR)
#define LWIS_PLATFORM_EVENT_ID_ISP_FE_CTX3_CDAF_PRIMARY \
	EVENT_ID(ISP_FE_LMP_BAYER_CTX3_BASE, \
		 ISP_FE_LMP_BAYER_CTX3_CDAF_PRIMARY)
#define LWIS_PLATFORM_EVENT_ID_ISP_FE_CTX3_CDAF_WINDOWS \
	EVENT_ID(ISP_FE_LMP_BAYER_CTX3_BASE, \
		 ISP_FE_LMP_BAYER_CTX3_CDAF_WINDOWS)
#define LWIS_PLATFORM_EVENT_ID_ISP_FE_CTX3_PRE_LSC_AE_STATS \
	EVENT_ID(ISP_FE_LMP_BAYER_CTX3_BASE, \
		 ISP_FE_LMP_BAYER_CTX3_PRE_LSC_AE_STATS)
#define LWIS_PLATFORM_EVENT_ID_ISP_FE_CTX3_AWB_STATS \
	EVENT_ID(ISP_FE_LMP_BAYER_CTX3_BASE, \
		 ISP_FE_LMP_BAYER_CTX3_AWB_STATS)
#define LWIS_PLATFORM_EVENT_ID_ISP_FE_CTX3_LSC_STATS \
	EVENT_ID(ISP_FE_LMP_BAYER_CTX3_BASE, \
		 ISP_FE_LMP_BAYER_CTX3_LSC_STATS)
#define LWIS_PLATFORM_EVENT_ID_ISP_FE_CTX3_FLICKER_STATS \
	EVENT_ID(ISP_FE_LMP_BAYER_CTX3_BASE, \
		 ISP_FE_LMP_BAYER_CTX3_FLICKER_STATS)
#define LWIS_PLATFORM_EVENT_ID_ISP_FE_CTX3_HISTOGRAM0 \
	EVENT_ID(ISP_FE_LMP_BAYER_CTX3_BASE, \
		 ISP_FE_LMP_BAYER_CTX3_HISTOGRAM0)
#define LWIS_PLATFORM_EVENT_ID_ISP_FE_CTX3_HISTOGRAM1 \
	EVENT_ID(ISP_FE_LMP_BAYER_CTX3_BASE, \
		 ISP_FE_LMP_BAYER_CTX3_HISTOGRAM1)
#define LWIS_PLATFORM_EVENT_ID_ISP_FE_CTX3_HISTOGRAM2 \
	EVENT_ID(ISP_FE_LMP_BAYER_CTX3_BASE, \
		 ISP_FE_LMP_BAYER_CTX3_HISTOGRAM2)
#define LWIS_PLATFORM_EVENT_ID_ISP_FE_CTX3_POST_LSC_AE_STATS \
	EVENT_ID(ISP_FE_LMP_BAYER_CTX3_BASE, \
		 ISP_FE_LMP_BAYER_CTX3_POST_LSC_AE_STATS)
#define LWIS_PLATFORM_EVENT_ID_ISP_FE_CTX3_MOTION_METERING \
	EVENT_ID(ISP_FE_LMP_BAYER_CTX3_BASE, \
		 ISP_FE_LMP_BAYER_CTX3_MOTION_METERING)
#define LWIS_PLATFORM_EVENT_ID_ISP_FE_CTX3_BAYER0_WDMA \
	EVENT_ID(ISP_FE_LMP_BAYER_CTX3_BASE, \
		 ISP_FE_LMP_BAYER_CTX3_BAYER0_WDMA)
#define LWIS_PLATFORM_EVENT_ID_ISP_FE_CTX3_BAYER1_WDMA \
	EVENT_ID(ISP_FE_LMP_BAYER_CTX3_BASE, \
		 ISP_FE_LMP_BAYER_CTX3_BAYER1_WDMA)
#define LWIS_PLATFORM_EVENT_ID_ISP_FE_CTX3_LINEAR_RGB_OUTPUT \
	EVENT_ID(ISP_FE_LMP_BAYER_CTX3_BASE, \
		 ISP_FE_LMP_BAYER_CTX3_LINEAR_RGB_OUTPUT)
#define LWIS_PLATFORM_EVENT_ID_ISP_FE_CTX3_ML_OUTPUT0 \
	EVENT_ID(ISP_FE_LMP_BAYER_CTX3_BASE, \
		 ISP_FE_LMP_BAYER_CTX3_ML_OUTPUT0)
#define LWIS_PLATFORM_EVENT_ID_ISP_FE_CTX3_ML_OUTPUT1 \
	EVENT_ID(ISP_FE_LMP_BAYER_CTX3_BASE, \
		 ISP_FE_LMP_BAYER_CTX3_ML_OUTPUT1)
#define LWIS_PLATFORM_EVENT_ID_ISP_FE_CTX3_ML_OUTPUT2 \
	EVENT_ID(ISP_FE_LMP_BAYER_CTX3_BASE, \
		 ISP_FE_LMP_BAYER_CTX3_ML_OUTPUT2)
#define LWIS_PLATFORM_EVENT_ID_ISP_FE_CTX3_TNR_PYRAMID \
	EVENT_ID(ISP_FE_LMP_BAYER_CTX3_BASE, \
		 ISP_FE_LMP_BAYER_CTX3_TNR_PYRAMID)
#define LWIS_PLATFORM_EVENT_ID_ISP_FE_CTX3_MERGE1 \
	EVENT_ID(ISP_FE_LMP_BAYER_CTX3_BASE, \
		 ISP_FE_LMP_BAYER_CTX3_MERGE1)
#define LWIS_PLATFORM_EVENT_ID_ISP_FE_CTX3_MERGE2 \
	EVENT_ID(ISP_FE_LMP_BAYER_CTX3_BASE, \
		 ISP_FE_LMP_BAYER_CTX3_MERGE2)
#define LWIS_PLATFORM_EVENT_ID_ISP_FE_CTX3_MERGE3 \
	EVENT_ID(ISP_FE_LMP_BAYER_CTX3_BASE, \
		 ISP_FE_LMP_BAYER_CTX3_MERGE3)
#define LWIS_PLATFORM_EVENT_ID_ISP_FE_CTX3_MERGE4 \
	EVENT_ID(ISP_FE_LMP_BAYER_CTX3_BASE, \
		 ISP_FE_LMP_BAYER_CTX3_MERGE4)
#define LWIS_PLATFORM_EVENT_ID_ISP_FE_CTX3_MERGE5 \
	EVENT_ID(ISP_FE_LMP_BAYER_CTX3_BASE, \
		 ISP_FE_LMP_BAYER_CTX3_MERGE5)
#define LWIS_PLATFORM_EVENT_ID_ISP_FE_CTX3_MERGE6 \
	EVENT_ID(ISP_FE_LMP_BAYER_CTX3_BASE, \
		 ISP_FE_LMP_BAYER_CTX3_MERGE6)
#define LWIS_PLATFORM_EVENT_ID_ISP_FE_CTX3_LMP_BUS_ERROR \
	EVENT_ID(ISP_FE_LMP_BAYER_CTX3_BASE, \
		 ISP_FE_LMP_BAYER_CTX3_LMP_BUS_ERROR)
#define LWIS_PLATFORM_EVENT_ID_ISP_FE_CTX3_SOF \
	EVENT_ID(ISP_FE_LMP_BAYER_CTX3_BASE, \
		 ISP_FE_LMP_BAYER_CTX3_SOF)

#define LWIS_PLATFORM_EVENT_ID_ISP_FE_CTX4_REGISTER_UPDATE \
	EVENT_ID(ISP_FE_LMP_BAYER_CTX4_BASE, \
		 ISP_FE_LMP_BAYER_CTX4_REGISTER_UPDATE)
#define LWIS_PLATFORM_EVENT_ID_ISP_FE_CTX4_EOF \
	EVENT_ID(ISP_FE_LMP_BAYER_CTX4_BASE, \
		 ISP_FE_LMP_BAYER_CTX4_EOF)
#define LWIS_PLATFORM_EVENT_ID_ISP_FE_CTX4_END_OF_BATCH \
	EVENT_ID(ISP_FE_LMP_BAYER_CTX4_BASE, \
		 ISP_FE_LMP_BAYER_CTX4_END_OF_BATCH)
#define LWIS_PLATFORM_EVENT_ID_ISP_FE_CTX4_FE_LMP_ERROR \
	EVENT_ID(ISP_FE_LMP_BAYER_CTX4_BASE, \
		 ISP_FE_LMP_BAYER_CTX4_FE_LMP_ERROR)
#define LWIS_PLATFORM_EVENT_ID_ISP_FE_CTX4_CDAF_PRIMARY \
	EVENT_ID(ISP_FE_LMP_BAYER_CTX4_BASE, \
		 ISP_FE_LMP_BAYER_CTX4_CDAF_PRIMARY)
#define LWIS_PLATFORM_EVENT_ID_ISP_FE_CTX4_CDAF_WINDOWS \
	EVENT_ID(ISP_FE_LMP_BAYER_CTX4_BASE, \
		 ISP_FE_LMP_BAYER_CTX4_CDAF_WINDOWS)
#define LWIS_PLATFORM_EVENT_ID_ISP_FE_CTX4_PRE_LSC_AE_STATS \
	EVENT_ID(ISP_FE_LMP_BAYER_CTX4_BASE, \
		 ISP_FE_LMP_BAYER_CTX4_PRE_LSC_AE_STATS)
#define LWIS_PLATFORM_EVENT_ID_ISP_FE_CTX4_AWB_STATS \
	EVENT_ID(ISP_FE_LMP_BAYER_CTX4_BASE, \
		 ISP_FE_LMP_BAYER_CTX4_AWB_STATS)
#define LWIS_PLATFORM_EVENT_ID_ISP_FE_CTX4_LSC_STATS \
	EVENT_ID(ISP_FE_LMP_BAYER_CTX4_BASE, \
		 ISP_FE_LMP_BAYER_CTX4_LSC_STATS)
#define LWIS_PLATFORM_EVENT_ID_ISP_FE_CTX4_FLICKER_STATS \
	EVENT_ID(ISP_FE_LMP_BAYER_CTX4_BASE, \
		 ISP_FE_LMP_BAYER_CTX4_FLICKER_STATS)
#define LWIS_PLATFORM_EVENT_ID_ISP_FE_CTX4_HISTOGRAM0 \
	EVENT_ID(ISP_FE_LMP_BAYER_CTX4_BASE, \
		 ISP_FE_LMP_BAYER_CTX4_HISTOGRAM0)
#define LWIS_PLATFORM_EVENT_ID_ISP_FE_CTX4_HISTOGRAM1 \
	EVENT_ID(ISP_FE_LMP_BAYER_CTX4_BASE, \
		 ISP_FE_LMP_BAYER_CTX4_HISTOGRAM1)
#define LWIS_PLATFORM_EVENT_ID_ISP_FE_CTX4_HISTOGRAM2 \
	EVENT_ID(ISP_FE_LMP_BAYER_CTX4_BASE, \
		 ISP_FE_LMP_BAYER_CTX4_HISTOGRAM2)
#define LWIS_PLATFORM_EVENT_ID_ISP_FE_CTX4_POST_LSC_AE_STATS \
	EVENT_ID(ISP_FE_LMP_BAYER_CTX4_BASE, \
		 ISP_FE_LMP_BAYER_CTX4_POST_LSC_AE_STATS)
#define LWIS_PLATFORM_EVENT_ID_ISP_FE_CTX4_MOTION_METERING \
	EVENT_ID(ISP_FE_LMP_BAYER_CTX4_BASE, \
		 ISP_FE_LMP_BAYER_CTX4_MOTION_METERING)
#define LWIS_PLATFORM_EVENT_ID_ISP_FE_CTX4_BAYER0_WDMA \
	EVENT_ID(ISP_FE_LMP_BAYER_CTX4_BASE, \
		 ISP_FE_LMP_BAYER_CTX4_BAYER0_WDMA)
#define LWIS_PLATFORM_EVENT_ID_ISP_FE_CTX4_BAYER1_WDMA \
	EVENT_ID(ISP_FE_LMP_BAYER_CTX4_BASE, \
		 ISP_FE_LMP_BAYER_CTX4_BAYER1_WDMA)
#define LWIS_PLATFORM_EVENT_ID_ISP_FE_CTX4_LINEAR_RGB_OUTPUT \
	EVENT_ID(ISP_FE_LMP_BAYER_CTX4_BASE, \
		 ISP_FE_LMP_BAYER_CTX4_LINEAR_RGB_OUTPUT)
#define LWIS_PLATFORM_EVENT_ID_ISP_FE_CTX4_ML_OUTPUT0 \
	EVENT_ID(ISP_FE_LMP_BAYER_CTX4_BASE, \
		 ISP_FE_LMP_BAYER_CTX4_ML_OUTPUT0)
#define LWIS_PLATFORM_EVENT_ID_ISP_FE_CTX4_ML_OUTPUT1 \
	EVENT_ID(ISP_FE_LMP_BAYER_CTX4_BASE, \
		 ISP_FE_LMP_BAYER_CTX4_ML_OUTPUT1)
#define LWIS_PLATFORM_EVENT_ID_ISP_FE_CTX4_ML_OUTPUT2 \
	EVENT_ID(ISP_FE_LMP_BAYER_CTX4_BASE, \
		 ISP_FE_LMP_BAYER_CTX4_ML_OUTPUT2)
#define LWIS_PLATFORM_EVENT_ID_ISP_FE_CTX4_TNR_PYRAMID \
	EVENT_ID(ISP_FE_LMP_BAYER_CTX4_BASE, \
		 ISP_FE_LMP_BAYER_CTX4_TNR_PYRAMID)
#define LWIS_PLATFORM_EVENT_ID_ISP_FE_CTX4_MERGE1 \
	EVENT_ID(ISP_FE_LMP_BAYER_CTX4_BASE, \
		 ISP_FE_LMP_BAYER_CTX4_MERGE1)
#define LWIS_PLATFORM_EVENT_ID_ISP_FE_CTX4_MERGE2 \
	EVENT_ID(ISP_FE_LMP_BAYER_CTX4_BASE, \
		 ISP_FE_LMP_BAYER_CTX4_MERGE2)
#define LWIS_PLATFORM_EVENT_ID_ISP_FE_CTX4_MERGE3 \
	EVENT_ID(ISP_FE_LMP_BAYER_CTX4_BASE, \
		 ISP_FE_LMP_BAYER_CTX4_MERGE3)
#define LWIS_PLATFORM_EVENT_ID_ISP_FE_CTX4_MERGE4 \
	EVENT_ID(ISP_FE_LMP_BAYER_CTX4_BASE, \
		 ISP_FE_LMP_BAYER_CTX4_MERGE4)
#define LWIS_PLATFORM_EVENT_ID_ISP_FE_CTX4_MERGE5 \
	EVENT_ID(ISP_FE_LMP_BAYER_CTX4_BASE, \
		 ISP_FE_LMP_BAYER_CTX4_MERGE5)
#define LWIS_PLATFORM_EVENT_ID_ISP_FE_CTX4_MERGE6 \
	EVENT_ID(ISP_FE_LMP_BAYER_CTX4_BASE, \
		 ISP_FE_LMP_BAYER_CTX4_MERGE6)
#define LWIS_PLATFORM_EVENT_ID_ISP_FE_CTX4_LMP_BUS_ERROR \
	EVENT_ID(ISP_FE_LMP_BAYER_CTX4_BASE, \
		 ISP_FE_LMP_BAYER_CTX4_LMP_BUS_ERROR)
#define LWIS_PLATFORM_EVENT_ID_ISP_FE_CTX4_SOF \
	EVENT_ID(ISP_FE_LMP_BAYER_CTX4_BASE, \
		 ISP_FE_LMP_BAYER_CTX4_SOF)

#define LWIS_PLATFORM_EVENT_ID_ISP_FE_CTX0_SOF \
	EVENT_ID(ISP_FE_LMP_PDAF_CTX0_BASE, \
		 ISP_FE_LMP_PDAF_CTX0_SOF)
#define LWIS_PLATFORM_EVENT_ID_ISP_FE_CTX0_EOF \
	EVENT_ID(ISP_FE_LMP_PDAF_CTX0_BASE, \
		 ISP_FE_LMP_PDAF_CTX0_EOF)
#define LWIS_PLATFORM_EVENT_ID_ISP_FE_CTX0_END_OF_BATCH \
	EVENT_ID(ISP_FE_LMP_PDAF_CTX0_BASE, \
		 ISP_FE_LMP_PDAF_CTX0_END_OF_BATCH)
#define LWIS_PLATFORM_EVENT_ID_ISP_FE_CTX0_EARLY \
	EVENT_ID(ISP_FE_LMP_PDAF_CTX0_BASE, \
		 ISP_FE_LMP_PDAF_CTX0_EARLY)
#define LWIS_PLATFORM_EVENT_ID_ISP_FE_CTX0_REGISTER_UPDATE \
	EVENT_ID(ISP_FE_LMP_PDAF_CTX0_BASE, \
		 ISP_FE_LMP_PDAF_CTX0_REGISTER_UPDATE)
#define LWIS_PLATFORM_EVENT_ID_ISP_FE_CTX0_ABORT_START \
	EVENT_ID(ISP_FE_LMP_PDAF_CTX0_BASE, \
		 ISP_FE_LMP_PDAF_CTX0_ABORT_START)
#define LWIS_PLATFORM_EVENT_ID_ISP_FE_CTX0_ABORT_DMA_COMPLETE \
	EVENT_ID(ISP_FE_LMP_PDAF_CTX0_BASE, \
		 ISP_FE_LMP_PDAF_CTX0_ABORT_DMA_COMPLETE)
#define LWIS_PLATFORM_EVENT_ID_ISP_FE_CTX0_ABORT_DONE \
	EVENT_ID(ISP_FE_LMP_PDAF_CTX0_BASE, \
		 ISP_FE_LMP_PDAF_CTX0_ABORT_DONE)
#define LWIS_PLATFORM_EVENT_ID_ISP_FE_CTX0_ERROR \
	EVENT_ID(ISP_FE_LMP_PDAF_CTX0_BASE, \
		 ISP_FE_LMP_PDAF_CTX0_ERROR)
#define LWIS_PLATFORM_EVENT_ID_ISP_FE_CTX0_BUS_ERROR \
	EVENT_ID(ISP_FE_LMP_PDAF_CTX0_BASE, \
		 ISP_FE_LMP_PDAF_CTX0_BUS_ERROR)

#define LWIS_PLATFORM_EVENT_ID_ISP_FE_CTX1_SOF \
	EVENT_ID(ISP_FE_LMP_PDAF_CTX1_BASE, \
		 ISP_FE_LMP_PDAF_CTX1_SOF)
#define LWIS_PLATFORM_EVENT_ID_ISP_FE_CTX1_EOF \
	EVENT_ID(ISP_FE_LMP_PDAF_CTX1_BASE, \
		 ISP_FE_LMP_PDAF_CTX1_EOF)
#define LWIS_PLATFORM_EVENT_ID_ISP_FE_CTX1_END_OF_BATCH \
	EVENT_ID(ISP_FE_LMP_PDAF_CTX1_BASE, \
		 ISP_FE_LMP_PDAF_CTX1_END_OF_BATCH)
#define LWIS_PLATFORM_EVENT_ID_ISP_FE_CTX1_EARLY \
	EVENT_ID(ISP_FE_LMP_PDAF_CTX1_BASE, \
		 ISP_FE_LMP_PDAF_CTX1_EARLY)
#define LWIS_PLATFORM_EVENT_ID_ISP_FE_CTX1_REGISTER_UPDATE \
	EVENT_ID(ISP_FE_LMP_PDAF_CTX1_BASE, \
		 ISP_FE_LMP_PDAF_CTX1_REGISTER_UPDATE)
#define LWIS_PLATFORM_EVENT_ID_ISP_FE_CTX1_ABORT_START \
	EVENT_ID(ISP_FE_LMP_PDAF_CTX1_BASE, \
		 ISP_FE_LMP_PDAF_CTX1_ABORT_START)
#define LWIS_PLATFORM_EVENT_ID_ISP_FE_CTX1_ABORT_DMA_COMPLETE \
	EVENT_ID(ISP_FE_LMP_PDAF_CTX1_BASE, \
		 ISP_FE_LMP_PDAF_CTX1_ABORT_DMA_COMPLETE)
#define LWIS_PLATFORM_EVENT_ID_ISP_FE_CTX1_ABORT_DONE \
	EVENT_ID(ISP_FE_LMP_PDAF_CTX1_BASE, \
		 ISP_FE_LMP_PDAF_CTX1_ABORT_DONE)
#define LWIS_PLATFORM_EVENT_ID_ISP_FE_CTX1_ERROR \
	EVENT_ID(ISP_FE_LMP_PDAF_CTX1_BASE, \
		 ISP_FE_LMP_PDAF_CTX1_ERROR)
#define LWIS_PLATFORM_EVENT_ID_ISP_FE_CTX1_BUS_ERROR \
	EVENT_ID(ISP_FE_LMP_PDAF_CTX1_BASE, \
		 ISP_FE_LMP_PDAF_CTX1_BUS_ERROR)

#define LWIS_PLATFORM_EVENT_ID_ISP_FE_CTX2_SOF \
	EVENT_ID(ISP_FE_LMP_PDAF_CTX2_BASE, \
		 ISP_FE_LMP_PDAF_CTX2_SOF)
#define LWIS_PLATFORM_EVENT_ID_ISP_FE_CTX2_EOF \
	EVENT_ID(ISP_FE_LMP_PDAF_CTX2_BASE, \
		 ISP_FE_LMP_PDAF_CTX2_EOF)
#define LWIS_PLATFORM_EVENT_ID_ISP_FE_CTX2_END_OF_BATCH \
	EVENT_ID(ISP_FE_LMP_PDAF_CTX2_BASE, \
		 ISP_FE_LMP_PDAF_CTX2_END_OF_BATCH)
#define LWIS_PLATFORM_EVENT_ID_ISP_FE_CTX2_EARLY \
	EVENT_ID(ISP_FE_LMP_PDAF_CTX2_BASE, \
		 ISP_FE_LMP_PDAF_CTX2_EARLY)
#define LWIS_PLATFORM_EVENT_ID_ISP_FE_CTX2_REGISTER_UPDATE \
	EVENT_ID(ISP_FE_LMP_PDAF_CTX2_BASE, \
		 ISP_FE_LMP_PDAF_CTX2_REGISTER_UPDATE)
#define LWIS_PLATFORM_EVENT_ID_ISP_FE_CTX2_ABORT_START \
	EVENT_ID(ISP_FE_LMP_PDAF_CTX2_BASE, \
		 ISP_FE_LMP_PDAF_CTX2_ABORT_START)
#define LWIS_PLATFORM_EVENT_ID_ISP_FE_CTX2_ABORT_DMA_COMPLETE \
	EVENT_ID(ISP_FE_LMP_PDAF_CTX2_BASE, \
		 ISP_FE_LMP_PDAF_CTX2_ABORT_DMA_COMPLETE)
#define LWIS_PLATFORM_EVENT_ID_ISP_FE_CTX2_ABORT_DONE \
	EVENT_ID(ISP_FE_LMP_PDAF_CTX2_BASE, \
		 ISP_FE_LMP_PDAF_CTX2_ABORT_DONE)
#define LWIS_PLATFORM_EVENT_ID_ISP_FE_CTX2_ERROR \
	EVENT_ID(ISP_FE_LMP_PDAF_CTX2_BASE, \
		 ISP_FE_LMP_PDAF_CTX2_ERROR)
#define LWIS_PLATFORM_EVENT_ID_ISP_FE_CTX2_BUS_ERROR \
	EVENT_ID(ISP_FE_LMP_PDAF_CTX2_BASE, \
		 ISP_FE_LMP_PDAF_CTX2_BUS_ERROR)

#define LWIS_PLATFORM_EVENT_ID_ISP_FE_CTX3_SOF \
	EVENT_ID(ISP_FE_LMP_PDAF_CTX3_BASE, \
		 ISP_FE_LMP_PDAF_CTX3_SOF)
#define LWIS_PLATFORM_EVENT_ID_ISP_FE_CTX3_EOF \
	EVENT_ID(ISP_FE_LMP_PDAF_CTX3_BASE, \
		 ISP_FE_LMP_PDAF_CTX3_EOF)
#define LWIS_PLATFORM_EVENT_ID_ISP_FE_CTX3_END_OF_BATCH \
	EVENT_ID(ISP_FE_LMP_PDAF_CTX3_BASE, \
		 ISP_FE_LMP_PDAF_CTX3_END_OF_BATCH)
#define LWIS_PLATFORM_EVENT_ID_ISP_FE_CTX3_EARLY \
	EVENT_ID(ISP_FE_LMP_PDAF_CTX3_BASE, \
		 ISP_FE_LMP_PDAF_CTX3_EARLY)
#define LWIS_PLATFORM_EVENT_ID_ISP_FE_CTX3_REGISTER_UPDATE \
	EVENT_ID(ISP_FE_LMP_PDAF_CTX3_BASE, \
		 ISP_FE_LMP_PDAF_CTX3_REGISTER_UPDATE)
#define LWIS_PLATFORM_EVENT_ID_ISP_FE_CTX3_ABORT_START \
	EVENT_ID(ISP_FE_LMP_PDAF_CTX3_BASE, \
		 ISP_FE_LMP_PDAF_CTX3_ABORT_START)
#define LWIS_PLATFORM_EVENT_ID_ISP_FE_CTX3_ABORT_DMA_COMPLETE \
	EVENT_ID(ISP_FE_LMP_PDAF_CTX3_BASE, \
		 ISP_FE_LMP_PDAF_CTX3_ABORT_DMA_COMPLETE)
#define LWIS_PLATFORM_EVENT_ID_ISP_FE_CTX3_ABORT_DONE \
	EVENT_ID(ISP_FE_LMP_PDAF_CTX3_BASE, \
		 ISP_FE_LMP_PDAF_CTX3_ABORT_DONE)
#define LWIS_PLATFORM_EVENT_ID_ISP_FE_CTX3_ERROR \
	EVENT_ID(ISP_FE_LMP_PDAF_CTX3_BASE, \
		 ISP_FE_LMP_PDAF_CTX3_ERROR)
#define LWIS_PLATFORM_EVENT_ID_ISP_FE_CTX3_BUS_ERROR \
	EVENT_ID(ISP_FE_LMP_PDAF_CTX3_BASE, \
		 ISP_FE_LMP_PDAF_CTX3_BUS_ERROR)

#define LWIS_PLATFORM_EVENT_ID_ISP_FE_HW_TIMEOUT \
	EVENT_ID(ISP_FE_LMP_DEBUG_BASE, \
		 ISP_FE_LMP_DEBUG_HW_TIMEOUT)
#define LWIS_PLATFORM_EVENT_ID_ISP_FE_HW_BUS_ERROR \
	EVENT_ID(ISP_FE_LMP_DEBUG_BASE, \
		 ISP_FE_LMP_DEBUG_HW_BUS_ERROR)
#define LWIS_PLATFORM_EVENT_ID_ISP_FE_HW_AXI_READ_DATA_OVERFLOW \
	EVENT_ID(ISP_FE_LMP_DEBUG_BASE, \
		 ISP_FE_LMP_DEBUG_HW_AXI_READ_DATA_OVERFLOW)
#define LWIS_PLATFORM_EVENT_ID_ISP_FE_HW_AXI_WRITE_DATA_UNDERFLOW \
	EVENT_ID(ISP_FE_LMP_DEBUG_BASE, \
		 ISP_FE_LMP_DEBUG_HW_AXI_WRITE_DATA_UNDERFLOW)
#define LWIS_PLATFORM_EVENT_ID_ISP_FE_HW_LUT_ILLEGAL_PROGRAMMING_NON_SEQ \
	EVENT_ID(ISP_FE_LMP_DEBUG_BASE, \
		 ISP_FE_LMP_DEBUG_HW_LUT_ILLEGAL_PROGRAMMING_NON_SEQ)
#define LWIS_PLATFORM_EVENT_ID_ISP_FE_HW_LUT_ILLEGAL_PROGRAMMING_NON_ATOMIC \
	EVENT_ID(ISP_FE_LMP_DEBUG_BASE, \
		 ISP_FE_LMP_DEBUG_HW_LUT_ILLEGAL_PROGRAMMING_NON_ATOMIC)
#define LWIS_PLATFORM_EVENT_ID_ISP_FE_HW_LUT_ILLEGAL_PROGRAMMING_PARTIAL_BAYER \
	EVENT_ID(ISP_FE_LMP_DEBUG_BASE, \
		 ISP_FE_LMP_DEBUG_HW_LUT_ILLEGAL_PROGRAMMING_PARTIAL_BAYER)
#define LWIS_PLATFORM_EVENT_ID_ISP_FE_HW_LUT_ILLEGAL_PROGRAMMING_PARTIAL_PDAF0 \
	EVENT_ID(ISP_FE_LMP_DEBUG_BASE, \
		 ISP_FE_LMP_DEBUG_HW_LUT_ILLEGAL_PROGRAMMING_PARTIAL_PDAF0)
#define LWIS_PLATFORM_EVENT_ID_ISP_FE_HW_LUT_ILLEGAL_PROGRAMMING_PARTIAL_PDAF1 \
	EVENT_ID(ISP_FE_LMP_DEBUG_BASE, \
		 ISP_FE_LMP_DEBUG_HW_LUT_ILLEGAL_PROGRAMMING_PARTIAL_PDAF1)
#define LWIS_PLATFORM_EVENT_ID_ISP_FE_HW_LUT_ILLEGAL_PROGRAMMING_PARTIAL_PDAF2 \
	EVENT_ID(ISP_FE_LMP_DEBUG_BASE, \
		 ISP_FE_LMP_DEBUG_HW_LUT_ILLEGAL_PROGRAMMING_PARTIAL_PDAF2)
#define LWIS_PLATFORM_EVENT_ID_ISP_FE_HW_LUT_ILLEGAL_PROGRAMMING_PARTIAL_PDAF3 \
	EVENT_ID(ISP_FE_LMP_DEBUG_BASE, \
		 ISP_FE_LMP_DEBUG_HW_LUT_ILLEGAL_PROGRAMMING_PARTIAL_PDAF3)
#define LWIS_PLATFORM_EVENT_ID_ISP_FE_HW_UNDEFINED \
	EVENT_ID(ISP_FE_LMP_DEBUG_BASE, \
		 ISP_FE_LMP_DEBUG_HW_UNDEFINED)

#endif /* DT_BINDINGS_LWIS_PLATFORM_ZUMA_ISP_FE_H_ */
