/* SPDX-License-Identifier: GPL-2.0-only */
/*
 * Google LWIS ZUMA ISP_FE Interrupt And Event Defines
 *
 * Copyright (c) 2022 Google, LLC
 */

#ifndef DT_BINDINGS_LWIS_PLATFORM_ZUMA_ISP_FE_H_
#define DT_BINDINGS_LWIS_PLATFORM_ZUMA_ISP_FE_H_

#include <dt-bindings/lwis/platform/common.h>

/* clang-format off */

#define ISP_FE_FC_BAYER_CTX0_BASE {HW_EVENT_MASK + 0}

#define ISP_FE_FC_BAYER_CTX0_FC_SOF 0
#define ISP_FE_FC_BAYER_CTX0_FC_EOF 1
#define ISP_FE_FC_BAYER_CTX0_FC_REG_UPDATED 2
#define ISP_FE_FC_BAYER_CTX0_FC_ABORT_START 3
#define ISP_FE_FC_BAYER_CTX0_FC_ABORT_DMA_CMPLT 4
#define ISP_FE_FC_BAYER_CTX0_FC_ABORT_DONE 5
#define ISP_FE_FC_BAYER_CTX0_FC_LATE_CONFIG 6
#define ISP_FE_FC_BAYER_CTX0_FC_ERROR 7
#define ISP_FE_FC_BAYER_CTX0_SPD_WDMA_BUS_ERROR 8
#define ISP_FE_FC_BAYER_CTX0_LMP_IDMA0_BUS_ERROR 9
#define ISP_FE_FC_BAYER_CTX0_LMP_IDMA1_BUS_ERROR 10

#define ISP_FE_FC_BAYER_CTX1_BASE {HW_EVENT_MASK + 32}

#define ISP_FE_FC_BAYER_CTX1_FC_SOF 0
#define ISP_FE_FC_BAYER_CTX1_FC_EOF 1
#define ISP_FE_FC_BAYER_CTX1_FC_REG_UPDATED 2
#define ISP_FE_FC_BAYER_CTX1_FC_ABORT_START 3
#define ISP_FE_FC_BAYER_CTX1_FC_ABORT_DMA_CMPLT 4
#define ISP_FE_FC_BAYER_CTX1_FC_ABORT_DONE 5
#define ISP_FE_FC_BAYER_CTX1_FC_LATE_CONFIG 6
#define ISP_FE_FC_BAYER_CTX1_FC_ERROR 7
#define ISP_FE_FC_BAYER_CTX1_SPD_WDMA_BUS_ERROR 8
#define ISP_FE_FC_BAYER_CTX1_LMP_IDMA0_BUS_ERROR 9
#define ISP_FE_FC_BAYER_CTX1_LMP_IDMA1_BUS_ERROR 10

#define ISP_FE_FC_BAYER_CTX2_BASE {HW_EVENT_MASK + 64}

#define ISP_FE_FC_BAYER_CTX2_FC_SOF 0
#define ISP_FE_FC_BAYER_CTX2_FC_EOF 1
#define ISP_FE_FC_BAYER_CTX2_FC_REG_UPDATED 2
#define ISP_FE_FC_BAYER_CTX2_FC_ABORT_START 3
#define ISP_FE_FC_BAYER_CTX2_FC_ABORT_DMA_CMPLT 4
#define ISP_FE_FC_BAYER_CTX2_FC_ABORT_DONE 5
#define ISP_FE_FC_BAYER_CTX2_FC_LATE_CONFIG 6
#define ISP_FE_FC_BAYER_CTX2_FC_ERROR 7
#define ISP_FE_FC_BAYER_CTX2_SPD_WDMA_BUS_ERROR 8
#define ISP_FE_FC_BAYER_CTX2_LMP_IDMA0_BUS_ERROR 9
#define ISP_FE_FC_BAYER_CTX2_LMP_IDMA1_BUS_ERROR 10

#define ISP_FE_FC_BAYER_CTX3_BASE {HW_EVENT_MASK + 96}

#define ISP_FE_FC_BAYER_CTX3_FC_SOF 0
#define ISP_FE_FC_BAYER_CTX3_FC_EOF 1
#define ISP_FE_FC_BAYER_CTX3_FC_REG_UPDATED 2
#define ISP_FE_FC_BAYER_CTX3_FC_ABORT_START 3
#define ISP_FE_FC_BAYER_CTX3_FC_ABORT_DMA_CMPLT 4
#define ISP_FE_FC_BAYER_CTX3_FC_ABORT_DONE 5
#define ISP_FE_FC_BAYER_CTX3_FC_LATE_CONFIG 6
#define ISP_FE_FC_BAYER_CTX3_FC_ERROR 7
#define ISP_FE_FC_BAYER_CTX3_SPD_WDMA_BUS_ERROR 8
#define ISP_FE_FC_BAYER_CTX3_LMP_IDMA0_BUS_ERROR 9
#define ISP_FE_FC_BAYER_CTX3_LMP_IDMA1_BUS_ERROR 10

#define ISP_FE_FC_BAYER_CTX4_BASE {HW_EVENT_MASK + 128}

#define ISP_FE_FC_BAYER_CTX4_FC_SOF 0
#define ISP_FE_FC_BAYER_CTX4_FC_EOF 1
#define ISP_FE_FC_BAYER_CTX4_FC_REG_UPDATED 2
#define ISP_FE_FC_BAYER_CTX4_FC_ABORT_START 3
#define ISP_FE_FC_BAYER_CTX4_FC_ABORT_DMA_CMPLT 4
#define ISP_FE_FC_BAYER_CTX4_FC_ABORT_DONE 5
#define ISP_FE_FC_BAYER_CTX4_FC_LATE_CONFIG 6
#define ISP_FE_FC_BAYER_CTX4_FC_ERROR 7
#define ISP_FE_FC_BAYER_CTX4_SPD_WDMA_BUS_ERROR 8
#define ISP_FE_FC_BAYER_CTX4_LMP_IDMA0_BUS_ERROR 9
#define ISP_FE_FC_BAYER_CTX4_LMP_IDMA1_BUS_ERROR 10

#define ISP_FE_FC_PDAF_CTX0_BASE {HW_EVENT_MASK + 160}

#define ISP_FE_FC_PDAF_CTX0_PDAF_LATE_CONFIG 0
#define ISP_FE_FC_PDAF_CTX0_PDAF_ERROR 1

#define ISP_FE_FC_PDAF_CTX1_BASE {HW_EVENT_MASK + 192}

#define ISP_FE_FC_PDAF_CTX1_PDAF_LATE_CONFIG 0
#define ISP_FE_FC_PDAF_CTX1_PDAF_ERROR 1

#define ISP_FE_FC_PDAF_CTX2_BASE {HW_EVENT_MASK + 224}

#define ISP_FE_FC_PDAF_CTX2_PDAF_LATE_CONFIG 0
#define ISP_FE_FC_PDAF_CTX2_PDAF_ERROR 1

#define ISP_FE_FC_PDAF_CTX3_BASE {HW_EVENT_MASK + 256}

#define ISP_FE_FC_PDAF_CTX3_PDAF_LATE_CONFIG 0
#define ISP_FE_FC_PDAF_CTX3_PDAF_ERROR 1

#define ISP_FE_PDMA_CTX0_BASE {HW_EVENT_MASK + 288}

#define ISP_FE_PDMA_CTX0_IRQ_CMD 0
#define ISP_FE_PDMA_CTX0_ALMOST_EMPTY 1

#define ISP_FE_PDMA_CTX1_BASE {HW_EVENT_MASK + 320}

#define ISP_FE_PDMA_CTX1_IRQ_CMD 0
#define ISP_FE_PDMA_CTX1_ALMOST_EMPTY 1

#define ISP_FE_PDMA_CTX2_BASE {HW_EVENT_MASK + 352}

#define ISP_FE_PDMA_CTX2_IRQ_CMD 0
#define ISP_FE_PDMA_CTX2_ALMOST_EMPTY 1

#define ISP_FE_PDMA_CTX3_BASE {HW_EVENT_MASK + 384}

#define ISP_FE_PDMA_CTX3_IRQ_CMD 0
#define ISP_FE_PDMA_CTX3_ALMOST_EMPTY 1

#define ISP_FE_PDMA_CTX4_BASE {HW_EVENT_MASK + 416}

#define ISP_FE_PDMA_CTX4_IRQ_CMD 0
#define ISP_FE_PDMA_CTX4_ALMOST_EMPTY 1

#define ISP_FE_PDMA_ERR_CTX0_BASE {HW_EVENT_MASK + 448}

#define ISP_FE_PDMA_ERR_CTX0_MEM_BUS_ERR 0
#define ISP_FE_PDMA_ERR_CTX0_CSR_BUS_ERR 1
#define ISP_FE_PDMA_ERR_CTX0_ILLEGAL_CMD 2
#define ISP_FE_PDMA_ERR_CTX0_RECUR_INDIR_CMD 3
#define ISP_FE_PDMA_ERR_CTX0_CMD_SIZE_MISMATCH 4

#define ISP_FE_PDMA_ERR_CTX1_BASE {HW_EVENT_MASK + 480}

#define ISP_FE_PDMA_ERR_CTX1_MEM_BUS_ERR 0
#define ISP_FE_PDMA_ERR_CTX1_CSR_BUS_ERR 1
#define ISP_FE_PDMA_ERR_CTX1_ILLEGAL_CMD 2
#define ISP_FE_PDMA_ERR_CTX1_RECUR_INDIR_CMD 3
#define ISP_FE_PDMA_ERR_CTX1_CMD_SIZE_MISMATCH 4

#define ISP_FE_PDMA_ERR_CTX2_BASE {HW_EVENT_MASK + 512}

#define ISP_FE_PDMA_ERR_CTX2_MEM_BUS_ERR 0
#define ISP_FE_PDMA_ERR_CTX2_CSR_BUS_ERR 1
#define ISP_FE_PDMA_ERR_CTX2_ILLEGAL_CMD 2
#define ISP_FE_PDMA_ERR_CTX2_RECUR_INDIR_CMD 3
#define ISP_FE_PDMA_ERR_CTX2_CMD_SIZE_MISMATCH 4

#define ISP_FE_PDMA_ERR_CTX3_BASE {HW_EVENT_MASK + 544}

#define ISP_FE_PDMA_ERR_CTX3_MEM_BUS_ERR 0
#define ISP_FE_PDMA_ERR_CTX3_CSR_BUS_ERR 1
#define ISP_FE_PDMA_ERR_CTX3_ILLEGAL_CMD 2
#define ISP_FE_PDMA_ERR_CTX3_RECUR_INDIR_CMD 3
#define ISP_FE_PDMA_ERR_CTX3_CMD_SIZE_MISMATCH 4

#define ISP_FE_PDMA_ERR_CTX4_BASE {HW_EVENT_MASK + 576}

#define ISP_FE_PDMA_ERR_CTX4_MEM_BUS_ERR 0
#define ISP_FE_PDMA_ERR_CTX4_CSR_BUS_ERR 1
#define ISP_FE_PDMA_ERR_CTX4_ILLEGAL_CMD 2
#define ISP_FE_PDMA_ERR_CTX4_RECUR_INDIR_CMD 3
#define ISP_FE_PDMA_ERR_CTX4_CMD_SIZE_MISMATCH 4

#define ISP_FE_PDMA_RSTCTL_CTX0_BASE {HW_EVENT_MASK + 608}

#define ISP_FE_PDMA_RSTCTL_CTX0_SW_RESET_DONE 0
#define ISP_FE_PDMA_RSTCTL_CTX0_INPUT_FLUSH_DONE 1
#define ISP_FE_PDMA_RSTCTL_CTX0_SW_MODE 2
#define ISP_FE_PDMA_RSTCTL_CTX0_APB_GKP_ERR 3
#define ISP_FE_PDMA_RSTCTL_CTX0_AXI_GKP_ERR 4

#define ISP_FE_PDMA_RSTCTL_CTX1_BASE {HW_EVENT_MASK + 640}

#define ISP_FE_PDMA_RSTCTL_CTX1_SW_RESET_DONE 0
#define ISP_FE_PDMA_RSTCTL_CTX1_INPUT_FLUSH_DONE 1
#define ISP_FE_PDMA_RSTCTL_CTX1_SW_MODE 2
#define ISP_FE_PDMA_RSTCTL_CTX1_APB_GKP_ERR 3
#define ISP_FE_PDMA_RSTCTL_CTX1_AXI_GKP_ERR 4

#define ISP_FE_PDMA_RSTCTL_CTX2_BASE {HW_EVENT_MASK + 672}

#define ISP_FE_PDMA_RSTCTL_CTX2_SW_RESET_DONE 0
#define ISP_FE_PDMA_RSTCTL_CTX2_INPUT_FLUSH_DONE 1
#define ISP_FE_PDMA_RSTCTL_CTX2_SW_MODE 2
#define ISP_FE_PDMA_RSTCTL_CTX2_APB_GKP_ERR 3
#define ISP_FE_PDMA_RSTCTL_CTX2_AXI_GKP_ERR 4

#define ISP_FE_PDMA_RSTCTL_CTX3_BASE {HW_EVENT_MASK + 704}

#define ISP_FE_PDMA_RSTCTL_CTX3_SW_RESET_DONE 0
#define ISP_FE_PDMA_RSTCTL_CTX3_INPUT_FLUSH_DONE 1
#define ISP_FE_PDMA_RSTCTL_CTX3_SW_MODE 2
#define ISP_FE_PDMA_RSTCTL_CTX3_APB_GKP_ERR 3
#define ISP_FE_PDMA_RSTCTL_CTX3_AXI_GKP_ERR 4

#define ISP_FE_PDMA_RSTCTL_CTX4_BASE {HW_EVENT_MASK + 736}

#define ISP_FE_PDMA_RSTCTL_CTX4_SW_RESET_DONE 0
#define ISP_FE_PDMA_RSTCTL_CTX4_INPUT_FLUSH_DONE 1
#define ISP_FE_PDMA_RSTCTL_CTX4_SW_MODE 2
#define ISP_FE_PDMA_RSTCTL_CTX4_APB_GKP_ERR 3
#define ISP_FE_PDMA_RSTCTL_CTX4_AXI_GKP_ERR 4

/* clang-format on */

#define LWIS_PLATFORM_EVENT_ID_ISP_FE_CTX0_FC_SOF \
	EVENT_ID(ISP_FE_FC_BAYER_CTX0_BASE, \
		 ISP_FE_FC_BAYER_CTX0_FC_SOF)
#define LWIS_PLATFORM_EVENT_ID_ISP_FE_CTX0_FC_EOF \
	EVENT_ID(ISP_FE_FC_BAYER_CTX0_BASE, \
		 ISP_FE_FC_BAYER_CTX0_FC_EOF)
#define LWIS_PLATFORM_EVENT_ID_ISP_FE_CTX0_FC_REG_UPDATED \
	EVENT_ID(ISP_FE_FC_BAYER_CTX0_BASE, \
		 ISP_FE_FC_BAYER_CTX0_FC_REG_UPDATED)
#define LWIS_PLATFORM_EVENT_ID_ISP_FE_CTX0_FC_ABORT_START \
	EVENT_ID(ISP_FE_FC_BAYER_CTX0_BASE, \
		 ISP_FE_FC_BAYER_CTX0_FC_ABORT_START)
#define LWIS_PLATFORM_EVENT_ID_ISP_FE_CTX0_FC_ABORT_DMA_CMPLT \
	EVENT_ID(ISP_FE_FC_BAYER_CTX0_BASE, \
		 ISP_FE_FC_BAYER_CTX0_FC_ABORT_DMA_CMPLT)
#define LWIS_PLATFORM_EVENT_ID_ISP_FE_CTX0_FC_ABORT_DONE \
	EVENT_ID(ISP_FE_FC_BAYER_CTX0_BASE, \
		 ISP_FE_FC_BAYER_CTX0_FC_ABORT_DONE)
#define LWIS_PLATFORM_EVENT_ID_ISP_FE_CTX0_FC_LATE_CONFIG \
	EVENT_ID(ISP_FE_FC_BAYER_CTX0_BASE, \
		 ISP_FE_FC_BAYER_CTX0_FC_LATE_CONFIG)
#define LWIS_PLATFORM_EVENT_ID_ISP_FE_CTX0_FC_ERROR \
	EVENT_ID(ISP_FE_FC_BAYER_CTX0_BASE, \
		 ISP_FE_FC_BAYER_CTX0_FC_ERROR)
#define LWIS_PLATFORM_EVENT_ID_ISP_FE_CTX0_SPD_WDMA_BUS_ERROR \
	EVENT_ID(ISP_FE_FC_BAYER_CTX0_BASE, \
		 ISP_FE_FC_BAYER_CTX0_SPD_WDMA_BUS_ERROR)
#define LWIS_PLATFORM_EVENT_ID_ISP_FE_CTX0_LMP_IDMA0_BUS_ERROR \
	EVENT_ID(ISP_FE_FC_BAYER_CTX0_BASE, \
		 ISP_FE_FC_BAYER_CTX0_LMP_IDMA0_BUS_ERROR)
#define LWIS_PLATFORM_EVENT_ID_ISP_FE_CTX0_LMP_IDMA1_BUS_ERROR \
	EVENT_ID(ISP_FE_FC_BAYER_CTX0_BASE, \
		 ISP_FE_FC_BAYER_CTX0_LMP_IDMA1_BUS_ERROR)

#define LWIS_PLATFORM_EVENT_ID_ISP_FE_CTX1_FC_SOF \
	EVENT_ID(ISP_FE_FC_BAYER_CTX1_BASE, \
		 ISP_FE_FC_BAYER_CTX1_FC_SOF)
#define LWIS_PLATFORM_EVENT_ID_ISP_FE_CTX1_FC_EOF \
	EVENT_ID(ISP_FE_FC_BAYER_CTX1_BASE, \
		 ISP_FE_FC_BAYER_CTX1_FC_EOF)
#define LWIS_PLATFORM_EVENT_ID_ISP_FE_CTX1_FC_REG_UPDATED \
	EVENT_ID(ISP_FE_FC_BAYER_CTX1_BASE, \
		 ISP_FE_FC_BAYER_CTX1_FC_REG_UPDATED)
#define LWIS_PLATFORM_EVENT_ID_ISP_FE_CTX1_FC_ABORT_START \
	EVENT_ID(ISP_FE_FC_BAYER_CTX1_BASE, \
		 ISP_FE_FC_BAYER_CTX1_FC_ABORT_START)
#define LWIS_PLATFORM_EVENT_ID_ISP_FE_CTX1_FC_ABORT_DMA_CMPLT \
	EVENT_ID(ISP_FE_FC_BAYER_CTX1_BASE, \
		 ISP_FE_FC_BAYER_CTX1_FC_ABORT_DMA_CMPLT)
#define LWIS_PLATFORM_EVENT_ID_ISP_FE_CTX1_FC_ABORT_DONE \
	EVENT_ID(ISP_FE_FC_BAYER_CTX1_BASE, \
		 ISP_FE_FC_BAYER_CTX1_FC_ABORT_DONE)
#define LWIS_PLATFORM_EVENT_ID_ISP_FE_CTX1_FC_LATE_CONFIG \
	EVENT_ID(ISP_FE_FC_BAYER_CTX1_BASE, \
		 ISP_FE_FC_BAYER_CTX1_FC_LATE_CONFIG)
#define LWIS_PLATFORM_EVENT_ID_ISP_FE_CTX1_FC_ERROR \
	EVENT_ID(ISP_FE_FC_BAYER_CTX1_BASE, \
		 ISP_FE_FC_BAYER_CTX1_FC_ERROR)
#define LWIS_PLATFORM_EVENT_ID_ISP_FE_CTX1_SPD_WDMA_BUS_ERROR \
	EVENT_ID(ISP_FE_FC_BAYER_CTX1_BASE, \
		 ISP_FE_FC_BAYER_CTX1_SPD_WDMA_BUS_ERROR)
#define LWIS_PLATFORM_EVENT_ID_ISP_FE_CTX1_LMP_IDMA0_BUS_ERROR \
	EVENT_ID(ISP_FE_FC_BAYER_CTX1_BASE, \
		 ISP_FE_FC_BAYER_CTX1_LMP_IDMA0_BUS_ERROR)
#define LWIS_PLATFORM_EVENT_ID_ISP_FE_CTX1_LMP_IDMA1_BUS_ERROR \
	EVENT_ID(ISP_FE_FC_BAYER_CTX1_BASE, \
		 ISP_FE_FC_BAYER_CTX1_LMP_IDMA1_BUS_ERROR)

#define LWIS_PLATFORM_EVENT_ID_ISP_FE_CTX2_FC_SOF \
	EVENT_ID(ISP_FE_FC_BAYER_CTX2_BASE, \
		 ISP_FE_FC_BAYER_CTX2_FC_SOF)
#define LWIS_PLATFORM_EVENT_ID_ISP_FE_CTX2_FC_EOF \
	EVENT_ID(ISP_FE_FC_BAYER_CTX2_BASE, \
		 ISP_FE_FC_BAYER_CTX2_FC_EOF)
#define LWIS_PLATFORM_EVENT_ID_ISP_FE_CTX2_FC_REG_UPDATED \
	EVENT_ID(ISP_FE_FC_BAYER_CTX2_BASE, \
		 ISP_FE_FC_BAYER_CTX2_FC_REG_UPDATED)
#define LWIS_PLATFORM_EVENT_ID_ISP_FE_CTX2_FC_ABORT_START \
	EVENT_ID(ISP_FE_FC_BAYER_CTX2_BASE, \
		 ISP_FE_FC_BAYER_CTX2_FC_ABORT_START)
#define LWIS_PLATFORM_EVENT_ID_ISP_FE_CTX2_FC_ABORT_DMA_CMPLT \
	EVENT_ID(ISP_FE_FC_BAYER_CTX2_BASE, \
		 ISP_FE_FC_BAYER_CTX2_FC_ABORT_DMA_CMPLT)
#define LWIS_PLATFORM_EVENT_ID_ISP_FE_CTX2_FC_ABORT_DONE \
	EVENT_ID(ISP_FE_FC_BAYER_CTX2_BASE, \
		 ISP_FE_FC_BAYER_CTX2_FC_ABORT_DONE)
#define LWIS_PLATFORM_EVENT_ID_ISP_FE_CTX2_FC_LATE_CONFIG \
	EVENT_ID(ISP_FE_FC_BAYER_CTX2_BASE, \
		 ISP_FE_FC_BAYER_CTX2_FC_LATE_CONFIG)
#define LWIS_PLATFORM_EVENT_ID_ISP_FE_CTX2_FC_ERROR \
	EVENT_ID(ISP_FE_FC_BAYER_CTX2_BASE, \
		 ISP_FE_FC_BAYER_CTX2_FC_ERROR)
#define LWIS_PLATFORM_EVENT_ID_ISP_FE_CTX2_SPD_WDMA_BUS_ERROR \
	EVENT_ID(ISP_FE_FC_BAYER_CTX2_BASE, \
		 ISP_FE_FC_BAYER_CTX2_SPD_WDMA_BUS_ERROR)
#define LWIS_PLATFORM_EVENT_ID_ISP_FE_CTX2_LMP_IDMA0_BUS_ERROR \
	EVENT_ID(ISP_FE_FC_BAYER_CTX2_BASE, \
		 ISP_FE_FC_BAYER_CTX2_LMP_IDMA0_BUS_ERROR)
#define LWIS_PLATFORM_EVENT_ID_ISP_FE_CTX2_LMP_IDMA1_BUS_ERROR \
	EVENT_ID(ISP_FE_FC_BAYER_CTX2_BASE, \
		 ISP_FE_FC_BAYER_CTX2_LMP_IDMA1_BUS_ERROR)

#define LWIS_PLATFORM_EVENT_ID_ISP_FE_CTX3_FC_SOF \
	EVENT_ID(ISP_FE_FC_BAYER_CTX3_BASE, \
		 ISP_FE_FC_BAYER_CTX3_FC_SOF)
#define LWIS_PLATFORM_EVENT_ID_ISP_FE_CTX3_FC_EOF \
	EVENT_ID(ISP_FE_FC_BAYER_CTX3_BASE, \
		 ISP_FE_FC_BAYER_CTX3_FC_EOF)
#define LWIS_PLATFORM_EVENT_ID_ISP_FE_CTX3_FC_REG_UPDATED \
	EVENT_ID(ISP_FE_FC_BAYER_CTX3_BASE, \
		 ISP_FE_FC_BAYER_CTX3_FC_REG_UPDATED)
#define LWIS_PLATFORM_EVENT_ID_ISP_FE_CTX3_FC_ABORT_START \
	EVENT_ID(ISP_FE_FC_BAYER_CTX3_BASE, \
		 ISP_FE_FC_BAYER_CTX3_FC_ABORT_START)
#define LWIS_PLATFORM_EVENT_ID_ISP_FE_CTX3_FC_ABORT_DMA_CMPLT \
	EVENT_ID(ISP_FE_FC_BAYER_CTX3_BASE, \
		 ISP_FE_FC_BAYER_CTX3_FC_ABORT_DMA_CMPLT)
#define LWIS_PLATFORM_EVENT_ID_ISP_FE_CTX3_FC_ABORT_DONE \
	EVENT_ID(ISP_FE_FC_BAYER_CTX3_BASE, \
		 ISP_FE_FC_BAYER_CTX3_FC_ABORT_DONE)
#define LWIS_PLATFORM_EVENT_ID_ISP_FE_CTX3_FC_LATE_CONFIG \
	EVENT_ID(ISP_FE_FC_BAYER_CTX3_BASE, \
		 ISP_FE_FC_BAYER_CTX3_FC_LATE_CONFIG)
#define LWIS_PLATFORM_EVENT_ID_ISP_FE_CTX3_FC_ERROR \
	EVENT_ID(ISP_FE_FC_BAYER_CTX3_BASE, \
		 ISP_FE_FC_BAYER_CTX3_FC_ERROR)
#define LWIS_PLATFORM_EVENT_ID_ISP_FE_CTX3_SPD_WDMA_BUS_ERROR \
	EVENT_ID(ISP_FE_FC_BAYER_CTX3_BASE, \
		 ISP_FE_FC_BAYER_CTX3_SPD_WDMA_BUS_ERROR)
#define LWIS_PLATFORM_EVENT_ID_ISP_FE_CTX3_LMP_IDMA0_BUS_ERROR \
	EVENT_ID(ISP_FE_FC_BAYER_CTX3_BASE, \
		 ISP_FE_FC_BAYER_CTX3_LMP_IDMA0_BUS_ERROR)
#define LWIS_PLATFORM_EVENT_ID_ISP_FE_CTX3_LMP_IDMA1_BUS_ERROR \
	EVENT_ID(ISP_FE_FC_BAYER_CTX3_BASE, \
		 ISP_FE_FC_BAYER_CTX3_LMP_IDMA1_BUS_ERROR)

#define LWIS_PLATFORM_EVENT_ID_ISP_FE_CTX4_FC_SOF \
	EVENT_ID(ISP_FE_FC_BAYER_CTX4_BASE, \
		 ISP_FE_FC_BAYER_CTX4_FC_SOF)
#define LWIS_PLATFORM_EVENT_ID_ISP_FE_CTX4_FC_EOF \
	EVENT_ID(ISP_FE_FC_BAYER_CTX4_BASE, \
		 ISP_FE_FC_BAYER_CTX4_FC_EOF)
#define LWIS_PLATFORM_EVENT_ID_ISP_FE_CTX4_FC_REG_UPDATED \
	EVENT_ID(ISP_FE_FC_BAYER_CTX4_BASE, \
		 ISP_FE_FC_BAYER_CTX4_FC_REG_UPDATED)
#define LWIS_PLATFORM_EVENT_ID_ISP_FE_CTX4_FC_ABORT_START \
	EVENT_ID(ISP_FE_FC_BAYER_CTX4_BASE, \
		 ISP_FE_FC_BAYER_CTX4_FC_ABORT_START)
#define LWIS_PLATFORM_EVENT_ID_ISP_FE_CTX4_FC_ABORT_DMA_CMPLT \
	EVENT_ID(ISP_FE_FC_BAYER_CTX4_BASE, \
		 ISP_FE_FC_BAYER_CTX4_FC_ABORT_DMA_CMPLT)
#define LWIS_PLATFORM_EVENT_ID_ISP_FE_CTX4_FC_ABORT_DONE \
	EVENT_ID(ISP_FE_FC_BAYER_CTX4_BASE, \
		 ISP_FE_FC_BAYER_CTX4_FC_ABORT_DONE)
#define LWIS_PLATFORM_EVENT_ID_ISP_FE_CTX4_FC_LATE_CONFIG \
	EVENT_ID(ISP_FE_FC_BAYER_CTX4_BASE, \
		 ISP_FE_FC_BAYER_CTX4_FC_LATE_CONFIG)
#define LWIS_PLATFORM_EVENT_ID_ISP_FE_CTX4_FC_ERROR \
	EVENT_ID(ISP_FE_FC_BAYER_CTX4_BASE, \
		 ISP_FE_FC_BAYER_CTX4_FC_ERROR)
#define LWIS_PLATFORM_EVENT_ID_ISP_FE_CTX4_SPD_WDMA_BUS_ERROR \
	EVENT_ID(ISP_FE_FC_BAYER_CTX4_BASE, \
		 ISP_FE_FC_BAYER_CTX4_SPD_WDMA_BUS_ERROR)
#define LWIS_PLATFORM_EVENT_ID_ISP_FE_CTX4_LMP_IDMA0_BUS_ERROR \
	EVENT_ID(ISP_FE_FC_BAYER_CTX4_BASE, \
		 ISP_FE_FC_BAYER_CTX4_LMP_IDMA0_BUS_ERROR)
#define LWIS_PLATFORM_EVENT_ID_ISP_FE_CTX4_LMP_IDMA1_BUS_ERROR \
	EVENT_ID(ISP_FE_FC_BAYER_CTX4_BASE, \
		 ISP_FE_FC_BAYER_CTX4_LMP_IDMA1_BUS_ERROR)

#define LWIS_PLATFORM_EVENT_ID_ISP_FE_CTX0_PDAF_LATE_CONFIG \
	EVENT_ID(ISP_FE_FC_PDAF_CTX0_BASE, \
		 ISP_FE_FC_PDAF_CTX0_PDAF_LATE_CONFIG)
#define LWIS_PLATFORM_EVENT_ID_ISP_FE_CTX0_PDAF_ERROR \
	EVENT_ID(ISP_FE_FC_PDAF_CTX0_BASE, \
		 ISP_FE_FC_PDAF_CTX0_PDAF_ERROR)

#define LWIS_PLATFORM_EVENT_ID_ISP_FE_CTX1_PDAF_LATE_CONFIG \
	EVENT_ID(ISP_FE_FC_PDAF_CTX1_BASE, \
		 ISP_FE_FC_PDAF_CTX1_PDAF_LATE_CONFIG)
#define LWIS_PLATFORM_EVENT_ID_ISP_FE_CTX1_PDAF_ERROR \
	EVENT_ID(ISP_FE_FC_PDAF_CTX1_BASE, \
		 ISP_FE_FC_PDAF_CTX1_PDAF_ERROR)

#define LWIS_PLATFORM_EVENT_ID_ISP_FE_CTX2_PDAF_LATE_CONFIG \
	EVENT_ID(ISP_FE_FC_PDAF_CTX2_BASE, \
		 ISP_FE_FC_PDAF_CTX2_PDAF_LATE_CONFIG)
#define LWIS_PLATFORM_EVENT_ID_ISP_FE_CTX2_PDAF_ERROR \
	EVENT_ID(ISP_FE_FC_PDAF_CTX2_BASE, \
		 ISP_FE_FC_PDAF_CTX2_PDAF_ERROR)

#define LWIS_PLATFORM_EVENT_ID_ISP_FE_CTX3_PDAF_LATE_CONFIG \
	EVENT_ID(ISP_FE_FC_PDAF_CTX3_BASE, \
		 ISP_FE_FC_PDAF_CTX3_PDAF_LATE_CONFIG)
#define LWIS_PLATFORM_EVENT_ID_ISP_FE_CTX3_PDAF_ERROR \
	EVENT_ID(ISP_FE_FC_PDAF_CTX3_BASE, \
		 ISP_FE_FC_PDAF_CTX3_PDAF_ERROR)

#define LWIS_PLATFORM_EVENT_ID_ISP_FE_CTX0_IRQ_CMD \
	EVENT_ID(ISP_FE_PDMA_CTX0_BASE, \
		 ISP_FE_PDMA_CTX0_IRQ_CMD)
#define LWIS_PLATFORM_EVENT_ID_ISP_FE_CTX0_ALMOST_EMPTY \
	EVENT_ID(ISP_FE_PDMA_CTX0_BASE, \
		 ISP_FE_PDMA_CTX0_ALMOST_EMPTY)

#define LWIS_PLATFORM_EVENT_ID_ISP_FE_CTX1_IRQ_CMD \
	EVENT_ID(ISP_FE_PDMA_CTX1_BASE, \
		 ISP_FE_PDMA_CTX1_IRQ_CMD)
#define LWIS_PLATFORM_EVENT_ID_ISP_FE_CTX1_ALMOST_EMPTY \
	EVENT_ID(ISP_FE_PDMA_CTX1_BASE, \
		 ISP_FE_PDMA_CTX1_ALMOST_EMPTY)

#define LWIS_PLATFORM_EVENT_ID_ISP_FE_CTX2_IRQ_CMD \
	EVENT_ID(ISP_FE_PDMA_CTX2_BASE, \
		 ISP_FE_PDMA_CTX2_IRQ_CMD)
#define LWIS_PLATFORM_EVENT_ID_ISP_FE_CTX2_ALMOST_EMPTY \
	EVENT_ID(ISP_FE_PDMA_CTX2_BASE, \
		 ISP_FE_PDMA_CTX2_ALMOST_EMPTY)

#define LWIS_PLATFORM_EVENT_ID_ISP_FE_CTX3_IRQ_CMD \
	EVENT_ID(ISP_FE_PDMA_CTX3_BASE, \
		 ISP_FE_PDMA_CTX3_IRQ_CMD)
#define LWIS_PLATFORM_EVENT_ID_ISP_FE_CTX3_ALMOST_EMPTY \
	EVENT_ID(ISP_FE_PDMA_CTX3_BASE, \
		 ISP_FE_PDMA_CTX3_ALMOST_EMPTY)

#define LWIS_PLATFORM_EVENT_ID_ISP_FE_CTX4_IRQ_CMD \
	EVENT_ID(ISP_FE_PDMA_CTX4_BASE, \
		 ISP_FE_PDMA_CTX4_IRQ_CMD)
#define LWIS_PLATFORM_EVENT_ID_ISP_FE_CTX4_ALMOST_EMPTY \
	EVENT_ID(ISP_FE_PDMA_CTX4_BASE, \
		 ISP_FE_PDMA_CTX4_ALMOST_EMPTY)

#define LWIS_PLATFORM_EVENT_ID_ISP_FE_CTX0_MEM_BUS_ERR \
	EVENT_ID(ISP_FE_PDMA_ERR_CTX0_BASE, \
		 ISP_FE_PDMA_ERR_CTX0_MEM_BUS_ERR)
#define LWIS_PLATFORM_EVENT_ID_ISP_FE_CTX0_CSR_BUS_ERR \
	EVENT_ID(ISP_FE_PDMA_ERR_CTX0_BASE, \
		 ISP_FE_PDMA_ERR_CTX0_CSR_BUS_ERR)
#define LWIS_PLATFORM_EVENT_ID_ISP_FE_CTX0_ILLEGAL_CMD \
	EVENT_ID(ISP_FE_PDMA_ERR_CTX0_BASE, \
		 ISP_FE_PDMA_ERR_CTX0_ILLEGAL_CMD)
#define LWIS_PLATFORM_EVENT_ID_ISP_FE_CTX0_RECUR_INDIR_CMD \
	EVENT_ID(ISP_FE_PDMA_ERR_CTX0_BASE, \
		 ISP_FE_PDMA_ERR_CTX0_RECUR_INDIR_CMD)
#define LWIS_PLATFORM_EVENT_ID_ISP_FE_CTX0_CMD_SIZE_MISMATCH \
	EVENT_ID(ISP_FE_PDMA_ERR_CTX0_BASE, \
		 ISP_FE_PDMA_ERR_CTX0_CMD_SIZE_MISMATCH)

#define LWIS_PLATFORM_EVENT_ID_ISP_FE_CTX1_MEM_BUS_ERR \
	EVENT_ID(ISP_FE_PDMA_ERR_CTX1_BASE, \
		 ISP_FE_PDMA_ERR_CTX1_MEM_BUS_ERR)
#define LWIS_PLATFORM_EVENT_ID_ISP_FE_CTX1_CSR_BUS_ERR \
	EVENT_ID(ISP_FE_PDMA_ERR_CTX1_BASE, \
		 ISP_FE_PDMA_ERR_CTX1_CSR_BUS_ERR)
#define LWIS_PLATFORM_EVENT_ID_ISP_FE_CTX1_ILLEGAL_CMD \
	EVENT_ID(ISP_FE_PDMA_ERR_CTX1_BASE, \
		 ISP_FE_PDMA_ERR_CTX1_ILLEGAL_CMD)
#define LWIS_PLATFORM_EVENT_ID_ISP_FE_CTX1_RECUR_INDIR_CMD \
	EVENT_ID(ISP_FE_PDMA_ERR_CTX1_BASE, \
		 ISP_FE_PDMA_ERR_CTX1_RECUR_INDIR_CMD)
#define LWIS_PLATFORM_EVENT_ID_ISP_FE_CTX1_CMD_SIZE_MISMATCH \
	EVENT_ID(ISP_FE_PDMA_ERR_CTX1_BASE, \
		 ISP_FE_PDMA_ERR_CTX1_CMD_SIZE_MISMATCH)

#define LWIS_PLATFORM_EVENT_ID_ISP_FE_CTX2_MEM_BUS_ERR \
	EVENT_ID(ISP_FE_PDMA_ERR_CTX2_BASE, \
		 ISP_FE_PDMA_ERR_CTX2_MEM_BUS_ERR)
#define LWIS_PLATFORM_EVENT_ID_ISP_FE_CTX2_CSR_BUS_ERR \
	EVENT_ID(ISP_FE_PDMA_ERR_CTX2_BASE, \
		 ISP_FE_PDMA_ERR_CTX2_CSR_BUS_ERR)
#define LWIS_PLATFORM_EVENT_ID_ISP_FE_CTX2_ILLEGAL_CMD \
	EVENT_ID(ISP_FE_PDMA_ERR_CTX2_BASE, \
		 ISP_FE_PDMA_ERR_CTX2_ILLEGAL_CMD)
#define LWIS_PLATFORM_EVENT_ID_ISP_FE_CTX2_RECUR_INDIR_CMD \
	EVENT_ID(ISP_FE_PDMA_ERR_CTX2_BASE, \
		 ISP_FE_PDMA_ERR_CTX2_RECUR_INDIR_CMD)
#define LWIS_PLATFORM_EVENT_ID_ISP_FE_CTX2_CMD_SIZE_MISMATCH \
	EVENT_ID(ISP_FE_PDMA_ERR_CTX2_BASE, \
		 ISP_FE_PDMA_ERR_CTX2_CMD_SIZE_MISMATCH)

#define LWIS_PLATFORM_EVENT_ID_ISP_FE_CTX3_MEM_BUS_ERR \
	EVENT_ID(ISP_FE_PDMA_ERR_CTX3_BASE, \
		 ISP_FE_PDMA_ERR_CTX3_MEM_BUS_ERR)
#define LWIS_PLATFORM_EVENT_ID_ISP_FE_CTX3_CSR_BUS_ERR \
	EVENT_ID(ISP_FE_PDMA_ERR_CTX3_BASE, \
		 ISP_FE_PDMA_ERR_CTX3_CSR_BUS_ERR)
#define LWIS_PLATFORM_EVENT_ID_ISP_FE_CTX3_ILLEGAL_CMD \
	EVENT_ID(ISP_FE_PDMA_ERR_CTX3_BASE, \
		 ISP_FE_PDMA_ERR_CTX3_ILLEGAL_CMD)
#define LWIS_PLATFORM_EVENT_ID_ISP_FE_CTX3_RECUR_INDIR_CMD \
	EVENT_ID(ISP_FE_PDMA_ERR_CTX3_BASE, \
		 ISP_FE_PDMA_ERR_CTX3_RECUR_INDIR_CMD)
#define LWIS_PLATFORM_EVENT_ID_ISP_FE_CTX3_CMD_SIZE_MISMATCH \
	EVENT_ID(ISP_FE_PDMA_ERR_CTX3_BASE, \
		 ISP_FE_PDMA_ERR_CTX3_CMD_SIZE_MISMATCH)

#define LWIS_PLATFORM_EVENT_ID_ISP_FE_CTX4_MEM_BUS_ERR \
	EVENT_ID(ISP_FE_PDMA_ERR_CTX4_BASE, \
		 ISP_FE_PDMA_ERR_CTX4_MEM_BUS_ERR)
#define LWIS_PLATFORM_EVENT_ID_ISP_FE_CTX4_CSR_BUS_ERR \
	EVENT_ID(ISP_FE_PDMA_ERR_CTX4_BASE, \
		 ISP_FE_PDMA_ERR_CTX4_CSR_BUS_ERR)
#define LWIS_PLATFORM_EVENT_ID_ISP_FE_CTX4_ILLEGAL_CMD \
	EVENT_ID(ISP_FE_PDMA_ERR_CTX4_BASE, \
		 ISP_FE_PDMA_ERR_CTX4_ILLEGAL_CMD)
#define LWIS_PLATFORM_EVENT_ID_ISP_FE_CTX4_RECUR_INDIR_CMD \
	EVENT_ID(ISP_FE_PDMA_ERR_CTX4_BASE, \
		 ISP_FE_PDMA_ERR_CTX4_RECUR_INDIR_CMD)
#define LWIS_PLATFORM_EVENT_ID_ISP_FE_CTX4_CMD_SIZE_MISMATCH \
	EVENT_ID(ISP_FE_PDMA_ERR_CTX4_BASE, \
		 ISP_FE_PDMA_ERR_CTX4_CMD_SIZE_MISMATCH)

#define LWIS_PLATFORM_EVENT_ID_ISP_FE_CTX0_SW_RESET_DONE \
	EVENT_ID(ISP_FE_PDMA_RSTCTL_CTX0_BASE, \
		 ISP_FE_PDMA_RSTCTL_CTX0_SW_RESET_DONE)
#define LWIS_PLATFORM_EVENT_ID_ISP_FE_CTX0_INPUT_FLUSH_DONE \
	EVENT_ID(ISP_FE_PDMA_RSTCTL_CTX0_BASE, \
		 ISP_FE_PDMA_RSTCTL_CTX0_INPUT_FLUSH_DONE)
#define LWIS_PLATFORM_EVENT_ID_ISP_FE_CTX0_SW_MODE \
	EVENT_ID(ISP_FE_PDMA_RSTCTL_CTX0_BASE, \
		 ISP_FE_PDMA_RSTCTL_CTX0_SW_MODE)
#define LWIS_PLATFORM_EVENT_ID_ISP_FE_CTX0_APB_GKP_ERR \
	EVENT_ID(ISP_FE_PDMA_RSTCTL_CTX0_BASE, \
		 ISP_FE_PDMA_RSTCTL_CTX0_APB_GKP_ERR)
#define LWIS_PLATFORM_EVENT_ID_ISP_FE_CTX0_AXI_GKP_ERR \
	EVENT_ID(ISP_FE_PDMA_RSTCTL_CTX0_BASE, \
		 ISP_FE_PDMA_RSTCTL_CTX0_AXI_GKP_ERR)

#define LWIS_PLATFORM_EVENT_ID_ISP_FE_CTX1_SW_RESET_DONE \
	EVENT_ID(ISP_FE_PDMA_RSTCTL_CTX1_BASE, \
		 ISP_FE_PDMA_RSTCTL_CTX1_SW_RESET_DONE)
#define LWIS_PLATFORM_EVENT_ID_ISP_FE_CTX1_INPUT_FLUSH_DONE \
	EVENT_ID(ISP_FE_PDMA_RSTCTL_CTX1_BASE, \
		 ISP_FE_PDMA_RSTCTL_CTX1_INPUT_FLUSH_DONE)
#define LWIS_PLATFORM_EVENT_ID_ISP_FE_CTX1_SW_MODE \
	EVENT_ID(ISP_FE_PDMA_RSTCTL_CTX1_BASE, \
		 ISP_FE_PDMA_RSTCTL_CTX1_SW_MODE)
#define LWIS_PLATFORM_EVENT_ID_ISP_FE_CTX1_APB_GKP_ERR \
	EVENT_ID(ISP_FE_PDMA_RSTCTL_CTX1_BASE, \
		 ISP_FE_PDMA_RSTCTL_CTX1_APB_GKP_ERR)
#define LWIS_PLATFORM_EVENT_ID_ISP_FE_CTX1_AXI_GKP_ERR \
	EVENT_ID(ISP_FE_PDMA_RSTCTL_CTX1_BASE, \
		 ISP_FE_PDMA_RSTCTL_CTX1_AXI_GKP_ERR)

#define LWIS_PLATFORM_EVENT_ID_ISP_FE_CTX2_SW_RESET_DONE \
	EVENT_ID(ISP_FE_PDMA_RSTCTL_CTX2_BASE, \
		 ISP_FE_PDMA_RSTCTL_CTX2_SW_RESET_DONE)
#define LWIS_PLATFORM_EVENT_ID_ISP_FE_CTX2_INPUT_FLUSH_DONE \
	EVENT_ID(ISP_FE_PDMA_RSTCTL_CTX2_BASE, \
		 ISP_FE_PDMA_RSTCTL_CTX2_INPUT_FLUSH_DONE)
#define LWIS_PLATFORM_EVENT_ID_ISP_FE_CTX2_SW_MODE \
	EVENT_ID(ISP_FE_PDMA_RSTCTL_CTX2_BASE, \
		 ISP_FE_PDMA_RSTCTL_CTX2_SW_MODE)
#define LWIS_PLATFORM_EVENT_ID_ISP_FE_CTX2_APB_GKP_ERR \
	EVENT_ID(ISP_FE_PDMA_RSTCTL_CTX2_BASE, \
		 ISP_FE_PDMA_RSTCTL_CTX2_APB_GKP_ERR)
#define LWIS_PLATFORM_EVENT_ID_ISP_FE_CTX2_AXI_GKP_ERR \
	EVENT_ID(ISP_FE_PDMA_RSTCTL_CTX2_BASE, \
		 ISP_FE_PDMA_RSTCTL_CTX2_AXI_GKP_ERR)

#define LWIS_PLATFORM_EVENT_ID_ISP_FE_CTX3_SW_RESET_DONE \
	EVENT_ID(ISP_FE_PDMA_RSTCTL_CTX3_BASE, \
		 ISP_FE_PDMA_RSTCTL_CTX3_SW_RESET_DONE)
#define LWIS_PLATFORM_EVENT_ID_ISP_FE_CTX3_INPUT_FLUSH_DONE \
	EVENT_ID(ISP_FE_PDMA_RSTCTL_CTX3_BASE, \
		 ISP_FE_PDMA_RSTCTL_CTX3_INPUT_FLUSH_DONE)
#define LWIS_PLATFORM_EVENT_ID_ISP_FE_CTX3_SW_MODE \
	EVENT_ID(ISP_FE_PDMA_RSTCTL_CTX3_BASE, \
		 ISP_FE_PDMA_RSTCTL_CTX3_SW_MODE)
#define LWIS_PLATFORM_EVENT_ID_ISP_FE_CTX3_APB_GKP_ERR \
	EVENT_ID(ISP_FE_PDMA_RSTCTL_CTX3_BASE, \
		 ISP_FE_PDMA_RSTCTL_CTX3_APB_GKP_ERR)
#define LWIS_PLATFORM_EVENT_ID_ISP_FE_CTX3_AXI_GKP_ERR \
	EVENT_ID(ISP_FE_PDMA_RSTCTL_CTX3_BASE, \
		 ISP_FE_PDMA_RSTCTL_CTX3_AXI_GKP_ERR)

#define LWIS_PLATFORM_EVENT_ID_ISP_FE_CTX4_SW_RESET_DONE \
	EVENT_ID(ISP_FE_PDMA_RSTCTL_CTX4_BASE, \
		 ISP_FE_PDMA_RSTCTL_CTX4_SW_RESET_DONE)
#define LWIS_PLATFORM_EVENT_ID_ISP_FE_CTX4_INPUT_FLUSH_DONE \
	EVENT_ID(ISP_FE_PDMA_RSTCTL_CTX4_BASE, \
		 ISP_FE_PDMA_RSTCTL_CTX4_INPUT_FLUSH_DONE)
#define LWIS_PLATFORM_EVENT_ID_ISP_FE_CTX4_SW_MODE \
	EVENT_ID(ISP_FE_PDMA_RSTCTL_CTX4_BASE, \
		 ISP_FE_PDMA_RSTCTL_CTX4_SW_MODE)
#define LWIS_PLATFORM_EVENT_ID_ISP_FE_CTX4_APB_GKP_ERR \
	EVENT_ID(ISP_FE_PDMA_RSTCTL_CTX4_BASE, \
		 ISP_FE_PDMA_RSTCTL_CTX4_APB_GKP_ERR)
#define LWIS_PLATFORM_EVENT_ID_ISP_FE_CTX4_AXI_GKP_ERR \
	EVENT_ID(ISP_FE_PDMA_RSTCTL_CTX4_BASE, \
		 ISP_FE_PDMA_RSTCTL_CTX4_AXI_GKP_ERR)

#endif /* DT_BINDINGS_LWIS_PLATFORM_ZUMA_ISP_FE_H_ */
