# SPDX-License-Identifier: GPL-2.0
#
# Makefile for multifunction miscellaneous devices
#

obj-$(CONFIG_MFD_S2MPG10) 		+= s2mpg10-mfd.o
s2mpg10-mfd-$(CONFIG_MFD_S2MPG10) 	+= s2mpg10-core.o s2mpg10-irq.o
obj-$(CONFIG_MFD_S2MPG11) 		+= s2mpg11-mfd.o
s2mpg11-mfd-$(CONFIG_MFD_S2MPG11) 	+= s2mpg11-core.o s2mpg11-irq.o
obj-$(CONFIG_MFD_S2MPG1X_GPIO) 	+= s2mpg1x-gpio.o

obj-$(CONFIG_MFD_SLG51000)	+= slg51000-core.o
